fix(licence): licence
linuxdeepin/dtkcore pull request #112
Opened 2022-09-21 05:53 UTC by Decodetalkers

README and licence under log folders

Log: fix licence

2022-09-22 06:33 UTC, kegechen commented
由于 LGPLv2 和 LGPLv3 兼容性问题存疑，暂时不合并

2022-09-28 01:28 UTC, BLumia requested changes

2022-09-28 01:28 UTC, BLumia commented on src/log/AbstractStringAppender.cpp
> +// SPDX-FileCopyrightText: 2021 - 2022 UnionTech Software Technology Co., Ltd.
原作者不是深度或者统信，不能随便把别人的 copyright 改成我们。

2022-10-21 06:43 UTC, BLumia approved these changes

2022-10-21 06:44 UTC, kegechen approved these changes

2022-10-21 06:44 UTC, merged