docs: update doxygen docs about dcifile
linuxdeepin/dtkcore pull request #136
Opened 2022-11-17 06:44 UTC by xzl01

更形dcifile文档

Log:

2022-11-17 07:35 UTC, zccrs requested changes
问题很多。大多数是通用的问题，根据评论修改即可，没有一一详细评论，要参考有详细评论的地方举一反三进行改动。

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 判断读取的dci文件是否有效
可以介绍的更详细些，不然看的时候给人的感觉就只是对函数名做了下翻译。比如这里可以举一些例子，“当制定的dci文件未成功加载时，此文件会返回false，一般会出现在文件格式错误（不是一个dci格式的文件），或者是dci文件数据被篡改而无法识别的情况”

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 获取上一个报错信息
跟上面那个一样，描述的太简单了。可以参考一下Qt里类似接口是怎么描述的。比如至少要说一下有哪些操作可能会出错，因为不是所有的操作都会产生错误，像调用 writeToFile 如果返回false，那应该会记录到 lastErrorString 里

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 写入文件
也是一样的问题，描述的太简单

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 写入到设备
同上

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 4+1+3 = 8
至少要介绍下什么是dci的metadata，这个data都是记录了啥

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 列出文件列表
也是描述的太简单

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 子文件计数
文档不应该只是陈述事实。要换个角度说，详细介绍下函数的意义和行为，特别是要包括临界情况时的处理方式。比如“返回指定的`dir`目录下的文件数量，也包括此目录下的文件夹。如果`dir`目录不存在，将返回？”，当目录不存在时具体返回啥从代码里看一下

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 子文件计数
dir这个目录不存在时就是一个临界情况

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 判断文件是否存在
同上

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@param[in] filePath:DCI图标结构路径
这里可以说是“DCI内部文件路径”，因为很多个函数的参数都有这个path，所以也应该在class的文档部分详细介绍下“DCI内部文件路径”的格式是什么，比如“使用'/'分割路径，从 "/" 开始”，还要包括文件路径中不能包含什么字符的介绍，以及路径最大长度，目录结尾要不要必须要有"/"覆盖这些事情。

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 判断文件类型
也是太简单了，参考前面的评论

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 获取文件的Ref信息
这个说法不对。这个函数的意义是以隐式引用的方式获取文件数据，如果调用方不修改返回的QByteArray对象，那就不会产生数据copy。

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 获取dci内文件的文件名
这里也说的不够清楚，比如什么叫“DCI内部文件的文件名”？包不包含文件后缀？而且dci和DCI使用时要统一，不要混用。

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 获取软链目标
描述的太模糊，可以参考QFileInfo的类似接口

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 创建目录
跟上面的一些接口是同样的问题，说的太简单了，只是对函数名翻译了一下，这样的文档没有意义。

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 写入文件
同上

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@param[in] override:是否覆盖，默认为否
同上，啥叫“覆盖”呢？要说清楚是“当文件已经存在时，是否要覆盖此文件，如果传入为true，则旧的文件数据将被清除，且无法恢复”

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 移除文件
同上

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 链接文件
同上

2022-11-17 07:35 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +*/
在尾部保留一个空行

2022-11-18 03:13 UTC, kegechen commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 判断读取的dci文件是否有效,当制定的dci文件未成功加载时,此函数会返回false,一般会出现在文件格式错误(不是一个dci格式的文件),或者是dci文件数据被篡改而无法识别的情况
zhiding

2022-11-18 03:17 UTC, zccrs requested changes

2022-11-18 03:17 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 判断读取的dci文件是否有效,当制定的dci文件未成功加载时,此函数会返回false,一般会出现在文件格式错误(不是一个dci格式的文件),或者是dci文件数据被篡改而无法识别的情况
","和"，"不要混用

2022-11-18 03:17 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 判断读取的dci文件是否有效,当制定的dci文件未成功加载时,此函数会返回false,一般会出现在文件格式错误(不是一个dci格式的文件),或者是dci文件数据被篡改而无法识别的情况
“制定”=》“指定”

2022-11-18 03:17 UTC, zccrs commented on docs/dci/ddcifile.zh_CN.dox
> +@brief 获取上一个报错信息,为人类可读字符串,可以通过此报错信息来判断错误内容,一般情况下是因为文件不存在或者文件名过长(>62个字符)导致。
有的尾部有句号，有的又没有，有标准吗？

2022-11-18 05:24 UTC, closed without merging