docs: add dconfig docs
linuxdeepin/dtkcore pull request #150
Opened 2022-11-23 08:48 UTC by chenchongbiao

添加dconfig文件文档注释

Log:

2022-11-23 08:52 UTC, chenchongbiao commented
I have read the CLA Document and I hereby sign the CLA.

2022-11-23 08:57 UTC, chenchongbiao commented
@xzl01

2022-11-24 00:36 UTC, 18202781743 commented on docs/global/dconfig.zh_CN.dox
> +@sa DConfigBackend::reset()
这种没有导出去的实现，应该不用在dox里加注释吧，

2022-11-24 01:27 UTC, BLumia commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
> This command is intended for use only when the language does not support the concept of pure virtual methods natively (e.g. C, PHP 4). -- [`\pure` 文档](https://www.doxygen.nl/manual/commands.html#cmdpure
)

还没本地尝试，不是很确定拆分出 .dox 进行 API 注释的情况是否需要刻意写 `@pure` 标注，随后我这边也会尝试下。如果根据文档描述的话，应该是不用刻意写的。

2022-11-24 02:43 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
好

2022-11-24 04:49 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
我看AbstractAppender.zh_CN的纯虚函数有加上这个，虚函数没加，那我保留纯虚函数的@pure 标注，虚函数的上的删去？

2022-11-24 05:43 UTC, BLumia commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
如果加不加都不会影响文档生成后的效果的话，可以都不加。（手头有点事，我可能晚点时候才会本地尝试。如果你这边已经试过的话也可以直接说下尝试的结果 :joy:）

2022-11-24 07:08 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
不会生成，有没有哪有教程看看，我没找到，我尝试用doxywizard可视化工具生成可以，我在那个docs目录，新建了个目录，进行cmake，生成那些文件，再用了make指令，好像并不是这样，make其他命令好像也不对。求教一下

2022-11-24 07:35 UTC, BLumia commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
是在构建依赖以及 doxygen 都装好的基础上，执行 cmake 的时候带上 `-DDOXYGEN_GENERATE_HTML="YES"` 参数进行配置，配置后会得到一个叫 `doxygen` 的目标，这时候是 `make doxygen` 生成文档，生成的文档会在 `docs/html` 目录下。

ps. 我们有开发者相关的在线讨论频道在 [`#deepin-community:matrix.org`](https://matrix.to/#/#deepin-community:matrix.org)，可以加进来一起讨论，会方便一些 :)

2022-11-24 07:37 UTC, Decodetalkers commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
> 

默认build_docs的开关是打开的,
```
cmake -B build
cmake --build build --target doxygen
cd build/docs/html
xdg-open index.html
```

2022-11-24 07:37 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
好的

2022-11-24 07:42 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
> > 
> 
> 默认build_docs的开关是打开的,你可以按照顺序在根目录执行以下命令
> 
> ```shell
> cmake -B build
> cmake --build build --target doxygen
> cd build/docs/html
> xdg-open index.html
> ```

好

2022-11-24 07:47 UTC, xzl01 commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
如果是查看主题是否正确的话 可以执行：`cmake -Bbuild -DBUILD_DOCS=1 -DBUILD_THEME=1` 然后再执行 `cmake --build build --target doxygen ` 最后打开`./build/docs/html/index.html`文件就可以看到文档效果了

2022-11-24 11:29 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@sa DConfigBackend::reset()
我构建了文档，那几个确实没导出，那我删一下

2022-11-25 04:03 UTC, BLumia requested changes
![图片](https://user-images.githubusercontent.com/10095765/203898970-a446779d-c972-4adc-a90a-acabda39f7da.png)

`@pure` 去掉吧，不主动标记也会识别到是 pure virtual（上图）。这个标注会导致函数签名前面多一个没意义的 pure（doxygen 原始目的是给不支持 pure 的语言做标记的）

另外参数里的注释要去掉（因为文档注释本身已经在注释块里了），不然会影响识别。

2022-11-25 04:03 UTC, BLumia commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure bool Dtk::Core::DConfigBackend::load(const QString &/*appId*/) = 0
```suggestion
@fn bool Dtk::Core::DConfigBackend::load(const QString &) = 0
```

2022-11-25 05:07 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure Dtk::Core::DConfigBackend::~DConfigBackend()
好

2022-11-25 05:08 UTC, chenchongbiao commented on docs/global/dconfig.zh_CN.dox
> +@fn @pure bool Dtk::Core::DConfigBackend::load(const QString &/*appId*/) = 0
好的 我修改下

2022-11-26 05:50 UTC, BLumia requested changes
`@param` 的标注方式是 `@param 参数名 说明文档`，参数名后面没有冒号。

另外，个人认为在没有刻意需要划分是传入参数还是传出参数的情况下，不需要刻意标 `[in]`，当然这个只是个人观点，可以保留你现状的写法。

最后，本地修改完去进行生成尝试的时候，可以留意下 log 输出，比如：

```
$ make doxygen 2>&1 | grep DConfigBackend
```

一些问题 doxygen 会给出警告（比如误用了冒号的情况），这样会更方便发现问题。

2022-11-26 05:50 UTC, BLumia commented on docs/global/dconfig.zh_CN.dox
> +@param[in] parent:父对象
```suggestion
@param[in] name 配置文件名
@param[in] subpath 配置文件对应的子目录
@param[in] parent 父对象
```

2022-11-26 08:38 UTC, BLumia approved these changes

2022-11-26 08:41 UTC, xzl01 approved these changes

2022-11-26 08:41 UTC, merged