chore dci tool and install dci cli tool
linuxdeepin/dtkcore pull request #184
Opened 2022-12-03 13:56 UTC by kegechen

1. add --tree args to view files in dci file
2. install dci cli tool in libdtkcore5-bin
3. fix invaild link when export dci file

2022-12-03 15:12 UTC, xzl01 approved these changes

2022-12-05 08:53 UTC, zccrs requested changes

2022-12-05 08:53 UTC, zccrs commented on tools/dci/main.cpp
> +    if (!info.isFile() || info.suffix() != "dci")
没必要判断这些，只要 dci.isValid 是true就够了

2022-12-06 09:18 UTC, zccrs approved these changes

2022-12-06 09:22 UTC, merged