feat: Add empty appid support for DConfig
linuxdeepin/dtkcore pull request #236
Opened 2023-01-11 01:18 UTC by 18202781743

All application use same configuration by empty appid.
  Loading cache file can fallback to noappid's directory when not
using appid or not find cache file.
  one application writes configuration.
  ```c++
  auto config = DConfig::create("", FileName);
  config->setValue("common-configuration", true);
  ```
  other applications read configration can give appid or not to
get the configuration.

Log: 配置策略支持空appid，缓存精准匹配到meta是否使用appid
Influence: none

Change-Id: I78b331f9c455617d5dfea6df087b1f4828390974

2023-02-03 02:54 UTC, kegechen submitted a review, later dismissed

2023-02-06 02:42 UTC, zccrs reviewed
为什么改动这么多呀，只添加一下 createGeneric 函数，内部的实现逻辑中允许 appid 为空不行吗，现在看来是针对  appid 为空的情况出了两套逻辑。

2023-02-06 02:51 UTC, black-desk commented on include/global/dconfig.h
> +    static DConfig *createGeneric(DConfigBackend *backend, const QString &name, const QString &subpath = QString(),
这样重载似乎是不如直接把backend做成可选参数

2023-02-06 02:51 UTC, black-desk commented on include/global/dconfigfile.h
> +    QVariant value(const QString &key, DConfigCache *userCache, bool *fromCache) const;
为什么不用可选参数? 以及fromcache这种东西是不是不应该传指针 而是传值

2023-02-06 03:50 UTC, asterwyx requested changes

2023-02-06 03:50 UTC, asterwyx commented on tests/ut_dconfig.cpp
> +    FileCopyGuard gurad(":/data/dconf-example.meta.json", noAppIdMetaFilePath);
```suggestion
    FileCopyGuard guard(":/data/dconf-example.meta.json", noAppIdMetaFilePath);
```

2023-02-06 03:50 UTC, asterwyx commented on tests/ut_dconfig.cpp
> +        ASSERT_EQ(config->value("key2"), "user-with-no-appid");
这里应该转为QString?

2023-02-06 03:50 UTC, asterwyx commented on tests/ut_dconfig.cpp
> +        ASSERT_EQ(config->value("key2"), "user-with-no-appid");
这里应该转为QString

2023-02-06 03:50 UTC, asterwyx commented on tests/ut_dconfigfile.cpp
> +    FileCopyGuard gurad(":/data/dconf-example.meta.json", QString("%1/%2.json").arg(noAppidMetaPath, FILE_NAME));
```suggestion
    FileCopyGuard guard(":/data/dconf-example.meta.json", QString("%1/%2.json").arg(noAppidMetaPath, FILE_NAME));
```

2023-02-06 03:50 UTC, asterwyx commented on tests/ut_dconfigfile.cpp
> +    FileCopyGuard gurad2(":/data/dconf-example.meta.json", QString("%1/%2.json").arg(metaPath, FILE_NAME));
typo

2023-02-06 05:57 UTC, 18202781743 commented on include/global/dconfigfile.h
> +    QVariant value(const QString &key, DConfigCache *userCache, bool *fromCache) const;
这里为了保持abi兼容，没有加默认参数去实现，fromcache是传出的值，不是传入的，

2023-02-06 05:57 UTC, 18202781743 commented on include/global/dconfig.h
> +    static DConfig *createGeneric(DConfigBackend *backend, const QString &name, const QString &subpath = QString(),
为了abi兼容

2023-02-06 05:57 UTC, 18202781743 commented on tests/ut_dconfig.cpp
> +        ASSERT_EQ(config->value("key2"), "user-with-no-appid");
QVariant可以与QString比较，可以转

2023-02-06 06:01 UTC, 18202781743 commented
> 为什么改动这么多呀，只添加一下 createGeneric 函数，内部的实现逻辑中允许 appid 为空不行吗，现在看来是针对 appid 为空的情况出了两套逻辑。

是的，大多不必要的更改撤销了，
dconfig使用FileBack时，value接口需要fallback到空appid，
需要添加一个value新的接口，供dde-dconfig-daemon使用，
另外想暴露metadirs接口，供editor查找存在的appid，

2023-02-06 06:12 UTC, black-desk commented on include/global/dconfig.h
> +    static DConfig *createGeneric(DConfigBackend *backend, const QString &name, const QString &subpath = QString(),
不是很理解 你这两个函数不都是新加的么?

2023-02-06 06:30 UTC, 18202781743 commented on include/global/dconfig.h
> +    static DConfig *createGeneric(DConfigBackend *backend, const QString &name, const QString &subpath = QString(),
createGeneric是和create对应的，
原来的create不把backend作为默认参数，是这个backend后来加的，为了保持abi兼容的，
另外，如果带backend函数用的少，parent与backend谁在前都不好定，如果用默认函数，使用另一个的时候需要显示指定null参数，

2023-02-06 07:22 UTC, asterwyx submitted a review, later dismissed

2023-02-07 08:35 UTC, zccrs requested changes

2023-02-07 08:35 UTC, zccrs commented on include/global/dconfigfile.h
> +    QVariant cacheValue(const QString &key, DConfigCache *userCache) const;
建议换一下俩参数的顺序，在 value 函数中之所以是key在前 userCache在后，是因为这里的userCache只是个可选的附属物，不是主角。但是在cacheValue中，userCache是主角。

2023-02-07 08:35 UTC, zccrs commented on src/dconfig.cpp
> +        if (owner->appId == GenericAppId)
这里应该是 != ？

2023-02-07 08:35 UTC, zccrs commented on src/dconfig.cpp
> +        if (canFallbackToInterapp) {
这是啥意思？Interapp拼错了？

2023-02-07 08:35 UTC, zccrs commented on src/dconfig.cpp
>          return v.isValid() ? v : fallback;
如果v无效，是不是还可以fallback到 genericConfigFile->value(

2023-02-07 09:32 UTC, 18202781743 commented on include/global/dconfigfile.h
> +    static QString genericAppId();
在daemon中会用到，用约定的空QString是不是不太好

2023-02-07 09:43 UTC, 18202781743 commented on src/dconfig.cpp
> +        if (canFallbackToInterapp) {
想提现应用间的配置，interapplication，这里还是统一改成generic吧

2023-02-07 09:44 UTC, 18202781743 commented on src/dconfig.cpp
> +        if (owner->appId == GenericAppId)
generic不需要fallback

2023-02-07 09:44 UTC, 18202781743 commented on src/dconfig.cpp
> +static QString GenericAppId = DConfigFile::genericAppId();
同上

2023-02-08 05:51 UTC, zccrs requested changes

2023-02-08 05:51 UTC, zccrs commented on include/global/dconfigfile.h
> +    static QString genericAppId();
没问题，如果这里设计提供了一个genericAppId，那就相当于把“与应用程序无关的通用性配置”这种东西定义为了一个特殊appid的特殊化处理。实际上，在标准文档中不应该这样定义，这种配置应该定义为“与应用程序无关”，而不是某个特殊应用程序的配置。在代码中可以明确appid为空时表示未指定appid，即可以理解为“与应用程序”无关。但是如果代码里没有这样明确下来，而是提供了一个函数，那意思就不一样了。

2023-02-08 05:51 UTC, zccrs commented on tests/ut_dconfig.cpp
> -        metaGuard = new FileCopyGuard(":/data/dconf-example.meta.json", QString("%1" PREFIX"/share/dsg/configs/%2/%3.json").arg(fileBackendLocalPerfix.value(), APP_ID, FILE_NAME));
为什么去掉了？

2023-02-13 10:10 UTC, 18202781743 commented on tests/ut_dconfig.cpp
> -        metaGuard = new FileCopyGuard(":/data/dconf-example.meta.json", QString("%1" PREFIX"/share/dsg/configs/%2/%3.json").arg(fileBackendLocalPerfix.value(), APP_ID, FILE_NAME));
改为了在指定单元测试中都执行，
因为加了新功能有的单元测试不需要拷贝这个文件了，

2023-02-14 05:42 UTC, zccrs requested changes

2023-02-14 05:42 UTC, zccrs commented on src/dconfig.cpp
> +static QString GenericAppId("");
连空字符串都不用，就应该是空的QString GenericAppId;

2023-02-14 05:42 UTC, zccrs commented on tests/ut_dconfigfile.cpp
> +        DConfigFile config(DConfigFile::genericAppId(), FILE_NAME);
DConfigFile::genericAppId 函数不是去掉了吗

2023-02-14 05:43 UTC, zccrs requested changes

2023-02-14 05:43 UTC, zccrs commented on include/global/dconfig.h
> +    static DConfig *createGeneric(const QString &name, const QString &subpath = QString(),
文档

2023-02-15 09:21 UTC, zccrs requested changes

2023-02-15 09:21 UTC, zccrs commented on docs/global/dconfigfile.zh_CN.dox
> +@brief DConfigFile::cacheValue 获取指定用户缓存的配置项值，若无此配置项的用户缓存值，返回空值
这里不应该是空值。而是返回一个无效值

2023-02-15 09:21 UTC, zccrs commented on src/dconfigfile.cpp
> + * @param userCache specic user cache, \a userCache is unused when the key is global
Specic应该是大写开头

2023-02-15 09:21 UTC, zccrs commented on tests/ut_dconfigfile.cpp
> +        DConfigFile config(GenericAppId, FILE_NAME);
建议 GenericAppId 改名较 NoAppId，不要让人误解为它是appid中的一个。另外这个变量在哪定义的话，没看到。

2023-02-15 15:56 UTC, asterwyx commented on src/dconfigfile.cpp
> + * @param userCache specic user cache, \a userCache is unused when the key is global
Specific

2023-02-16 01:39 UTC, zccrs approved these changes

2023-02-16 06:20 UTC, kegechen approved these changes

2023-02-16 09:41 UTC, asterwyx approved these changes

2023-02-16 09:41 UTC, merged