fix: Removing strong dependencies on systemd
linuxdeepin/dtkcore pull request #253
Opened 2023-02-03 08:08 UTC by xzl01

去除对systemd的强依赖

Log:

2023-02-03 08:19 UTC, asterwyx requested changes

2023-02-03 08:19 UTC, asterwyx commented on src/CMakeLists.txt
> +    pkg_check_modules(JOURNALD REQUIRED IMPORTED_TARGET libsystemd)
改成Systemd

2023-02-03 08:19 UTC, asterwyx commented on src/CMakeLists.txt
> +
删除这行

2023-02-03 08:45 UTC, kegechen commented on src/log/LogManager.cpp
> +#ifdef __BUILD_WITH_SYSTEMD
1.  __BUILD_WITH_SYSTEMD 没有定义吧，写错了？
2. 是不是可以用  #if (defined AAA && BBB)

2023-02-03 09:15 UTC, asterwyx reviewed
/+1

2023-02-06 01:20 UTC, xzl01 commented on src/log/LogManager.cpp
> +#ifdef __BUILD_WITH_SYSTEMD
#if defined(BUILD_WITH_SYSTEMD) && defined (Q_OS_LINUX)

2023-02-06 05:50 UTC, kegechen approved these changes

2023-02-06 06:14 UTC, asterwyx requested changes

2023-02-06 06:14 UTC, asterwyx commented on src/log/LogManager.cpp
> +#if  (defined BUILD_WITH_SYSTEMD && defined Q_OS_LINUX)
这一行的空格是不是有点问题

2023-02-06 06:14 UTC, asterwyx commented on src/log/LogManager.cpp
> +#if  (defined BUILD_WITH_SYSTEMD && defined Q_OS_LINUX)
```suggestion
#if (defined BUILD_WITH_SYSTEMD && defined Q_OS_LINUX)
```

2023-02-06 06:34 UTC, Decodetalkers commented
emm,如果不是必选。。那么ci时候会不会使用systemd？这个PKGBUILD主要是给ci用的，另外是发行版打包参考用的。。我觉得加注释就好

2023-02-06 06:36 UTC, Decodetalkers commented on archlinux/PKGBUILD
> +      -DBUILD_WITH_SYSTEMD
-DBUILD_WITH_SYSTEMD=ON

2023-02-06 06:37 UTC, asterwyx requested changes

2023-02-06 06:37 UTC, asterwyx commented on archlinux/PKGBUILD
> +
去掉这一行

2023-02-06 06:37 UTC, asterwyx commented on archlinux/PKGBUILD
> +      -DBUILD_WITH_SYSTEMD
```suggestion
      -DBUILD_WITH_SYSTEMD=ON
```

2023-02-06 06:45 UTC, asterwyx commented
既然现在并不是去除强依赖了，建议修改一下log信息和对应的PR介绍。

2023-02-06 07:23 UTC, asterwyx approved these changes

2023-02-06 07:24 UTC, merged