feat: support Qt6
linuxdeepin/dtkcore pull request #260
Opened 2023-02-08 07:33 UTC by ComixHe

Log: 支持Qt6

2023-02-08 08:04 UTC, Groveer commented on CMakeLists.txt
> +if(BUILD_QT_VERSION STREQUAL "6")
组合字符

2023-02-08 08:04 UTC, Groveer commented on CMakeLists.txt
> +  set(QT_MAJOR_VERSION 6)
QT_MAJOR_VERSION 变量错误？

2023-02-08 08:04 UTC, Groveer commented on docs/CMakeLists.txt
> +set(QCH_INSTALL_DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/qt5/doc CACHE STRING "QCH install location")
qt6 路径好像改为qt/doc了

2023-02-08 08:23 UTC, kegechen commented on CMakeLists.txt
> +#  find_package(QT NAMES Qt5 REQUIRED COMPONENTS Core)
删了呗

2023-02-08 08:37 UTC, Groveer commented on CMakeLists.txt
> +#if(BUILD_QT_VERSION STREQUAL "6")
注释删掉

2023-02-08 08:37 UTC, Groveer commented on misc/DtkCoreConfig.cmake.in
> +    find_dependency(Qt5DBus)
cmake文件也要跟着改

2023-02-08 08:37 UTC, Groveer commented on rpm/dtkcore.spec
> +Requires:       qt6-qtbase-devel%{?_isa}
rpm暂时不要动，保持跟archlinux一致

2023-02-08 08:37 UTC, Groveer commented on src/CMakeLists.txt
> +      pkg_check_modules(QGSettings REQUIRED gsettings-qt)
加个注释，dtk6 需要去掉 gsettings依赖

2023-02-08 08:37 UTC, Groveer commented on src/dbus/dbus.cmake
> +  qt6_add_dbus_interface(dbus_SRCS
qt6_add_dbus_interface 可改为 qt_add_dbus_interface

2023-02-08 08:37 UTC, Groveer commented on src/dbus/dbus.cmake
> +  qt6_add_dbus_interface(dbus_SRCS
同上

2023-02-08 08:37 UTC, Groveer commented on src/dci/private/ddcifileengine.cpp
> +        if (permissions) {
能否使用三元运算符

2023-02-08 08:37 UTC, Groveer commented on src/dsecurestring.cpp
> -    DUtil::SecureErase(*this);
如果include没有被外部使用，可删除该方法

2023-02-08 08:37 UTC, Groveer commented on src/dsysinfo.cpp
> +#include <QRegularExpression>
qt5是否有QRegularExpression 是否可以统一

2023-02-08 08:37 UTC, Groveer commented on src/util/dtextencoding.cpp
> +#include <climits>
如果没用可以删除

2023-02-08 08:38 UTC, Groveer commented on docs/CMakeLists.txt
> +set(QCH_INSTALL_DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/qt5/doc CACHE STRING "QCH install location")
qt6 改为doc/qt6了

2023-02-08 09:19 UTC, zccrs requested changes
先加这些。剩余的还没看。

2023-02-08 09:19 UTC, zccrs commented on src/dci/ddcifile.cpp
> +                if (path.mid(pathStart, 3) == QLatin1String("../")) {
这样直接把midRef替换为mid，在行为上就有变化了。应该用 QStringView 代替。

2023-02-08 09:19 UTC, zccrs commented on src/dci/ddcifile.cpp
> +    return !!(d->root);
为什么？有警告还是？

2023-02-08 09:19 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +#include <filesystem>
加个注释说明下为什么要这样做

2023-02-08 09:19 UTC, zccrs commented on src/dci/private/ddcifileengine_p.h
> -
无意义的改动

2023-02-08 09:19 UTC, zccrs commented on src/dconfigfile.cpp
> +                #if QT_VERSION > QT_VERSION_CHECK(6, 0, 0)
#if 放到一行的开头，前面不要空白字符。另外这里应该是 >= 吗？

2023-02-08 09:19 UTC, zccrs commented on src/dconfigfile.cpp
> +                #else
同上

2023-02-08 09:19 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +#if QT_VERSION > QT_VERSION_CHECK(6,0,0)
这种判断用到的还是比较多的，建议加一个专门的宏，比如在Qt6的环境下定义一个 IS_QT6 这样的宏。代码里直接用 #ifdef IS_QT6 这样判断。
另外，这里应该是 >= 吗？

2023-02-08 09:24 UTC, ComixHe commented on rpm/dtkcore.spec
> +Requires:       qt6-qtbase-devel%{?_isa}
已修改

2023-02-08 09:32 UTC, ComixHe commented on examples/textcodec-example/CMakeLists.txt
> +    Qt${QT_VERSION_MAJOR}::Core5Compat
加到了src下的cmake文件中

2023-02-08 09:39 UTC, ComixHe commented on src/CMakeLists.txt
> +set(QGSettings_hdr_dir)
已修复

2023-02-08 09:54 UTC, ComixHe commented on examples/dasync-example/main.cpp
> -#pragma mark main1 ------------------------------------------------------------
之前为了减少编译器警告，已还原

2023-02-08 09:55 UTC, ComixHe commented on archlinux/PKGBUILD
> +      -DBUILD_QT_VERSION=5
修改为CMAKE中变量默认为五

2023-02-08 10:00 UTC, ComixHe commented on include/util/dvtablehook.h
> +        if (fun1_offset > UINT_LEAST16_MAX)
已恢复

2023-02-08 10:02 UTC, ComixHe commented on CMakeLists.txt
> +set (MKSPECS_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/qt${BUILD_QT_VERSION}/mkspecs/modules" CACHE STRING "Install dir for qt pri files")
这个提交先不做，@asterwyx 说他后面会做，需要调研一下

2023-02-08 10:04 UTC, ComixHe commented on src/dci/ddcifile.cpp
> +    return !!(d->root);
c++17对于隐式转换有一个按上下文转换，现在必须要提供一个bool上下文才能隐式转换

2023-02-09 14:45 UTC, asterwyx requested changes

2023-02-09 14:45 UTC, asterwyx commented on CMakeLists.txt
> +message("current Qt Version: ${QT_VERSION_MAJOR}")
这里的提示注意下，别太随意了，句子首字母大写，version是不需要首字母大写的

2023-02-09 14:45 UTC, asterwyx commented on CMakeLists.txt
> +find_package(QT NAMES Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core)
既然已经直接set了QT_VERSION_MAJOR，这一行就是多余的。

2023-02-09 15:46 UTC, asterwyx requested changes

2023-02-09 15:46 UTC, asterwyx commented on include/util/dutil.h
> -
这应该是导出的头文件吧，直接删除岂不是连api都不兼容了，更不用说abi了。

2023-02-09 15:46 UTC, asterwyx commented on misc/DtkCoreConfig.cmake.in
> +@QT_VERSION_MAJOR@
这一行是多余的，去掉。

2023-02-09 15:46 UTC, asterwyx commented on misc/DtkCoreConfig.cmake.in
> +find_dependency(Qt@QT_VERSION_MAJOR@Core)
如果是Qt6，是不是还要考虑寻找Qt6Core5Compat的依赖。

2023-02-09 15:46 UTC, asterwyx commented on src/CMakeLists.txt
> +set(QT)
这一行存在的意义是什么。

2023-02-09 15:46 UTC, asterwyx commented on src/CMakeLists.txt
> +      pkg_check_modules(QGSettings REQUIRED IMPORTED_TARGET gsettings-qt) #Dtk6 removed.
升级刀Qt6就算升级到Dtk6了吗？

2023-02-09 15:46 UTC, asterwyx commented on src/CMakeLists.txt
> +    ${QGSettings_lib}
后面已经链接过PkgConfig::QGSettings了。

2023-02-09 15:46 UTC, asterwyx commented on src/dci/ddcifile.cpp
> +    return !!(d->root);
既然如此，建议不要使用隐式转换，直接写明条件表达式。

2023-02-09 15:46 UTC, asterwyx commented on src/dci/private/ddcifileengine.cpp
> +#if QT_VERSION >QT_VERSION_CHECK(6, 4, 0)
这里是不是也应该是>=

2023-02-09 15:46 UTC, asterwyx commented on src/dci/private/ddcifileengine.cpp
> +#if QT_VERSION >= QT_VERSION_CHECK(6,4, 0)
宏里面的空格注意一下

2023-02-09 15:46 UTC, asterwyx commented on src/dci/private/ddcifileengine_p.h
> -
这改动怎么还在呢。

2023-02-09 15:46 UTC, asterwyx commented on src/ddesktopentry.cpp
> +#else
这里是为什么

2023-02-09 15:46 UTC, asterwyx commented on src/ddesktopentry.cpp
> +#endif
感觉这里不用区分版本，可以写成统一形式。

2023-02-09 15:46 UTC, asterwyx commented on src/log/Logger.cpp
> +    appenderList.insert(v);
缩进

2023-02-09 15:46 UTC, asterwyx commented on src/log/RollingFileAppender.cpp
> +        m_rollOverTime = QDateTime::fromSecsSinceEpoch(0);
这里注意一下，有一个MSec和一个Sec，检查一下时间是否正确。

2023-02-09 15:46 UTC, asterwyx commented on tests/CMakeLists.txt
> +    pkg_check_modules(QGSettings REQUIRED gsettings-qt)
这里也可以IMPORTED_TARGET

2023-02-09 15:46 UTC, asterwyx commented on tests/CMakeLists.txt
> +endif()
感觉这一部分还是太麻烦了，直接以QT版本来决定是否链接就可以了。

2023-02-09 15:46 UTC, asterwyx commented on tests/CMakeLists.txt
> +    ${enable_QGsettings_hdr}
最好还是用target的方式链接，而且QGSettings相关的header不能开放出去。

2023-02-09 15:46 UTC, asterwyx commented on tests/ut_dutil.cpp
> -    delete DSingleton<int>::instance();
这里为什么要删除。

2023-02-09 15:46 UTC, asterwyx commented on tools/CMakeLists.txt
> +endif()
同样，这里太复杂了。

2023-02-09 15:46 UTC, asterwyx commented on tools/deepin-os-release/CMakeLists.txt
> +  ${Qt6Core_PRIVATE_INCLUDE_DIRS}
这里应该直接链接Qt6::CorePrivate，没有用是什么原因？

2023-02-09 15:46 UTC, asterwyx commented on tools/settings/CMakeLists.txt
> +set(QGSettings_lib)
同上。

2023-02-10 01:50 UTC, ComixHe commented on include/log/Logger.h
> +    QElapsedTimer m_time;
并不是获取现在的时间，这里以前主要是使用start和elapsed这两个方法来获取两次调用之间经过的时间，

2023-02-10 01:54 UTC, ComixHe commented on src/CMakeLists.txt
> +set(QT)
无意义，已删除

2023-02-10 01:56 UTC, ComixHe commented on src/CMakeLists.txt
> +      pkg_check_modules(QGSettings REQUIRED IMPORTED_TARGET gsettings-qt) #Dtk6 removed.
完全不兼容Qt5的时候就算升级到Qt6,目前只是支持Qt6

2023-02-10 01:58 UTC, ComixHe commented on src/CMakeLists.txt
> +    ${QGSettings_lib}
后更改的地方漏移除了

2023-02-10 02:08 UTC, ComixHe commented on src/ddesktopentry.cpp
> +#else
Qt6中QByteArray的append只支持QByteArray了

2023-02-10 02:09 UTC, ComixHe commented on src/ddesktopentry.cpp
> +#endif
已修改

2023-02-10 02:10 UTC, ComixHe commented on src/log/Logger.cpp
> +    appenderList.insert(v);
已修改

2023-02-10 02:12 UTC, ComixHe commented on src/log/RollingFileAppender.cpp
> +        m_rollOverTime = QDateTime::fromSecsSinceEpoch(0);
正确，都是秒

2023-02-10 02:16 UTC, ComixHe commented on tests/CMakeLists.txt
> +endif()
之前修改了，这里漏移除了，现已修改

2023-02-10 02:22 UTC, ComixHe commented on tools/deepin-os-release/CMakeLists.txt
> +  ${Qt6Core_PRIVATE_INCLUDE_DIRS}
已修改

2023-02-10 02:42 UTC, zccrs requested changes

2023-02-10 02:42 UTC, zccrs commented on CMakeLists.txt
> +set(QT_VERSION_MAJOR "5" CACHE STRING "Qt Version")
这里是不是应该判断下 QT_VERSION_MAJOR 是否已经被设置，如果没有设置才默认设置为 5

2023-02-10 02:42 UTC, zccrs commented on include/log/JournalAppender.h
> -                        const QString &msg);
不要偷懒。像这类完全没有相关性的改动最好是分开提交。

2023-02-10 02:42 UTC, zccrs commented on include/util/dutil.h
> -
那现在也不能直接删除，我们无法确定在dtk之外的项目中没有被用到

2023-02-10 02:42 UTC, zccrs commented on src/CMakeLists.txt
> +set(QT)
这是？

2023-02-10 02:42 UTC, zccrs commented on src/CMakeLists.txt
> +    if("${QT_VERSION_MAJOR}" STREQUAL "5")
缩进错了？

2023-02-10 02:42 UTC, zccrs commented on src/dci/ddcifile.cpp
> +                if (path.mid(pathStart, 3) == QLatin1String("../")) {
没看到这里改了呀

2023-02-10 02:42 UTC, zccrs commented on src/ddesktopentry.cpp
> +#else
那就不用判断Qt版本了，统一改成append QByteArray。另外这里是不是不应该是 toUtf8，而是toLocal8Bit

2023-02-10 02:42 UTC, zccrs commented on src/ddesktopentry.cpp
> +#endif
代码没提交上来？没看到改变

2023-02-10 02:42 UTC, zccrs commented on src/dsecurestring.cpp
> -    DUtil::SecureErase(*this);
没办法判断有没有被外部使用

2023-02-10 02:42 UTC, zccrs commented on src/log/AbstractStringAppender.cpp
> -            register char c = info.at(pos);
这个变化是？

2023-02-10 02:42 UTC, zccrs commented on src/util/ddbusextendedabstractinterface.cpp
> +        return QVariant{metaProperty.metaType(), propertyPtr};
这含义变了吧，Qt6中不是还有 userType吗，为什么需要替换为 metaType()?

2023-02-10 02:42 UTC, zccrs commented on src/util/ddbusinterface.cpp
> +        typeName = dbusMetaType.name();
这里的if包含的范围是不是太大了，至少这两行看着还是完全一样的

2023-02-10 02:42 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        qWarning() << "Is not a virtual function, function address: 0x" << Qt::hex << functionOffset;
会不会破坏在5.11上的兼容性？

2023-02-10 02:42 UTC, zccrs commented on src/ddesktopentry.cpp
> +    0,
这是用了自动格式化？先自己在本地diff下看看，不应该出现这类改动。

2023-02-10 02:42 UTC, zccrs commented on src/ddesktopentry.cpp
> +    0,
不要依赖于工具，最好是写代码时自己手动控制风格。避免让工具改动了未修改过的代码，即便那些旧代码的style有问题也应该是单独一个提交再去纠正。

2023-02-10 02:42 UTC, zccrs commented on src/ddesktopentry.cpp
> +QString &doEscape(QString &str, const QHash<QChar, QChar> &repl)
同上。这个提交要干干净净的只做一个目标，不要混入不相关的改动。

2023-02-10 02:42 UTC, zccrs commented on src/dsysinfo.cpp
> +#include <QRegularExpression>
可以统一

2023-02-10 02:42 UTC, zccrs commented on tests/ut_dfilesystemwatcher.cpp
> +#if QT_VERSION >= QT_VERSION_CHECK(6,0,0)
也加上注释说明为什么要额外include一个不需要的头文件

2023-02-10 05:54 UTC, asterwyx commented on src/CMakeLists.txt
> +      pkg_check_modules(QGSettings REQUIRED IMPORTED_TARGET gsettings-qt) #Dtk6 removed.
改一下这个注释

2023-02-10 05:59 UTC, ComixHe commented on src/CMakeLists.txt
> +set(QT)
这里重新提交了，需要刷新一下

2023-02-10 06:03 UTC, ComixHe commented on CMakeLists.txt
> +set(QT_VERSION_MAJOR "5" CACHE STRING "Qt Version")
这是个CACHE的变量，如果已经设置，他会沿用那个设置，不需要检查

2023-02-10 06:16 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +        qWarning() << "Is not a virtual function, function address: 0x" << Qt::hex << functionOffset;
看了一下是在5.14引入，已修改

2023-02-10 06:22 UTC, ComixHe commented on src/ddesktopentry.cpp
> +    0,
已修改

2023-02-10 06:26 UTC, ComixHe commented on include/util/dutil.h
> -
已更新

2023-02-10 06:32 UTC, ComixHe commented on src/log/AbstractStringAppender.cpp
> -            register char c = info.at(pos);
c++17不允许register作为修饰变量的关键字出现

2023-02-10 06:36 UTC, ComixHe commented on src/util/ddbusextendedabstractinterface.cpp
> +        return QVariant{metaProperty.metaType(), propertyPtr};
Qt6中QVariant的构造改了，不支持用type的id和dataPtr去构造一个Qvariant

2023-02-10 07:09 UTC, zccrs requested changes

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> -                          std::bind(doDeleteSharedDciFile, dciFilePath,
不必要的改动？

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +        if (paths.first.isEmpty() || paths.second.isEmpty())
同上

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +        } else {  // DDciFile::UnknowFile
同上

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> -    if ((openMode & QIODevice::ExistingOnly)
同上

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +            realDciFile.setFileName(dciFilePath);
跟186行重复了

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +        if (openMode & QIODevice::WriteOnly) {
在 6.4.0 版本中不需要进行这个判断吗？

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +        if (!file->exists(subfilePath) && !file->writeFile(subfilePath, QByteArray())) {
不必要的代码改动

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +        case AbsoluteName:
不必要的代码改动

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +    if (paths.first.isEmpty() || paths.second.isEmpty())
同上

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +QPair<QString, QString> DDciFileEngine::resolvePath(const QString &fullPath, const QString &realFilePath, bool needRealFileExists)
同上

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine.cpp
> +    qCDebug(
同上

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine_p.h
> +
同上

2023-02-10 07:09 UTC, zccrs commented on src/dci/private/ddcifileengine_p.h
> +
同上，还有其他地方就不一一标出来了。

2023-02-10 09:25 UTC, ComixHe commented on src/dci/ddcifile.cpp
> +                if (path.mid(pathStart, 3) == QLatin1String("../")) {
改成了mid

2023-02-10 11:20 UTC, ComixHe commented on src/dci/private/ddcifileengine.cpp
> +            realDciFile.setFileName(dciFilePath);
已修改

2023-02-10 11:23 UTC, ComixHe commented on src/dci/private/ddcifileengine.cpp
> +        if (openMode & QIODevice::WriteOnly) {
由189行判断，后续不同只涉及打开文件时的权限不同

2023-02-13 05:30 UTC, zccrs requested changes

2023-02-13 05:30 UTC, zccrs commented on src/dci/ddcifile.cpp
> +                if (path.mid(pathStart, 3) == QLatin1String("../")) {
pathView.mid

还有其他地方就不一一标记了

2023-02-13 05:30 UTC, zccrs commented on tests/ut_dconfigfile.cpp
> +#define type type
else 时就不需要定义了吧。另外加个注释说明下这个宏的用途，毕竟这个目的比较奇怪。

2023-02-13 09:09 UTC, asterwyx submitted a review, later dismissed

2023-02-13 11:01 UTC, ComixHe commented on src/dci/ddcifile.cpp
> +                if (path.mid(pathStart, 3) == QLatin1String("../")) {
最后return的时候还是用的path,用pathView还需要再toString才能拼接

2023-02-14 03:26 UTC, zccrs approved these changes

2023-02-14 03:27 UTC, zccrs commented
这里只是代码上支持了在Qt6的环境中构建。为了今后能一直维护对Qt6的兼容，CI中也要支持构建出Qt6相应的dtk包。

2023-02-14 05:22 UTC, merged