feat: dplugin
linuxdeepin/dtkcore pull request #262
Opened 2023-02-09 10:22 UTC by black-desk

- build: clean cmakelist
- feat: start impl dplugin

2023-02-16 13:44 UTC, black-desk commented
@kegechen @zccrs @Groveer @justforlxz 

这边希望给 DTK 添加一个通用的插件寻找机制, 方便需要使用插件来加载可选功能的应用编写.

这个机制目前设计如下:

应用会从 QT 给的 AppDataLocation 目录下的 plugins 文件夹中寻找配置文件. 配置文件中记录该插件的名称 版本和库名(也可以是绝对路径). 这些信息被用来初始化一个 QLibrary 对象. 需要加载插件的应用使用这个对象来工作.

这种设计参考了 chrome 以及 fcitx 的设计, 这两个项目都没有采取固定位置直接放置 so 库的做法, 而是采取了如此通过配置文件来寻找真正要使用的插件的做法.

由于 AppDataLocation 尊重 XDG_DATA_DIR 环境变量[^1], 如此设计对于需要更改插件实际存放位置的情况来说比较友好.

[^1]: https://github.com/qt/qtbase/blob/d7e8d5bb1b5a9c4b21a3d824780c672eaf4e56b1/src/corelib/io/qstandardpaths_unix.cpp#L374

2023-02-20 03:07 UTC, zccrs commented
> @kegechen @zccrs @Groveer @justforlxz
> 
> 这边希望给 DTK 添加一个通用的插件寻找机制, 方便需要使用插件来加载可选功能的应用编写.
> 
> 这个机制目前设计如下:
> 
> 应用会从 QT 给的 AppDataLocation 目录下的 plugins 文件夹中寻找配置文件. 配置文件中记录该插件的名称 版本和库名(也可以是绝对路径). 这些信息被用来初始化一个 QLibrary 对象. 需要加载插件的应用使用这个对象来工作.
> 
> 这种设计参考了 chrome 以及 fcitx 的设计, 这两个项目都没有采取固定位置直接放置 so 库的做法, 而是采取了如此通过配置文件来寻找真正要使用的插件的做法.
> 
> 由于 AppDataLocation 尊重 XDG_DATA_DIR 环境变量[1](#user-content-fn-1-ef367d9d4c265b44ae4545d5ab4528d6), 如此设计对于需要更改插件实际存放位置的情况来说比较友好.
> 
> ## Footnotes
> 1. https://github.com/qt/qtbase/blob/d7e8d5bb1b5a9c4b21a3d824780c672eaf4e56b1/src/corelib/io/qstandardpaths_unix.cpp#L374 [leftwards_arrow_with_hook](#user-content-fnref-1-ef367d9d4c265b44ae4545d5ab4528d6)

为什么不直接使用 QPluginLoader 呢

2023-02-20 07:45 UTC, black-desk commented
> 为什么不直接使用 QPluginLoader 呢

重点并不在于加载库的具体过程，而在于插件加载的过程需要：
1. 尊重XDG_DATA_DIRS环境变量
2. 方便具体的库位置移动
这对nix/flatpak以及玲珑类的打包方式都很有意义。

2023-02-23 05:48 UTC, asterwyx requested changes

2023-02-23 05:48 UTC, asterwyx commented on src/util/util.cmake
> +  set(UTILS_SOURCE ${UTILS_SOURCE}
I recommend using list(APPEND).

2023-02-23 05:48 UTC, asterwyx commented on include/util/dplugin.h
> +class DPlugin : public QObject
Should DPlugin derive from DObject? If yes, it's better to use D_DECLARE_PRIVATE. And remember to make DPluginPrivate derive from DObjectPrivate.

2023-03-29 08:05 UTC, black-desk commented
想了想好像解决不了插件里面又加载了其他的so的问题, 我再考虑考虑怎么解决 这个先挂着

2023-07-17 01:15 UTC, kegechen commented on src/util/dplugin.cpp
> +    auto const entryList = pluginDir.entryList();
可以通过 `QDir::FilterFiles::Files` 过滤一下，下面就不用判断是不是文件了

2023-07-17 01:19 UTC, kegechen commented on src/util/dplugin.cpp
> +    if (!DPluginPrivate::configCompatible(config["pluginConfigVersion"])) {
- json 的示例文件可以在注释或者什么地方提供一下。
- 既然已知是 plugin 的配置文件，是不是 json 中的 key 可以去掉 plugin 的前缀

2023-07-17 01:21 UTC, kegechen commented on src/util/dplugin.cpp
> +QList<std::shared_ptr<DPlugin>> DPluginPrivate::searchPluginsInPath(const QString &pluginDirPath)
```suggestion
QList<std::shared_ptr<DPlugin>> DPluginPrivate::load(const QString &pluginDirPath)
```

2024-06-01 13:17 UTC, closed without merging