chore: log file function and line by default
linuxdeepin/dtkcore pull request #263
Opened 2023-02-10 01:26 UTC by kegechen

add QT_MESSAGELOGCONTEXT dfinetions by default
log file function line by default

Log: log
Change-Id: I119eb2ffe4ac3d372fba874b99b9fc75131c0d6e

2023-02-10 02:58 UTC, zccrs requested changes

2023-02-10 02:58 UTC, zccrs commented on misc/dtkcore.pc.in
> +Cflags: -I${includedir} -DQT_MESSAGELOGCONTEXT
可以在邮件列表中探讨一下，这毕竟扩大了影响范围，不只是dtk自己的行为会变化。

2023-02-13 07:14 UTC, kegechen commented on misc/dtkcore.pc.in
> +Cflags: -I${includedir} -DQT_MESSAGELOGCONTEXT
ok

2023-02-16 03:56 UTC, zccrs approved these changes

2023-02-16 06:21 UTC, merged