feat: Support cache to be relocated for DConfigFile
linuxdeepin/dtkcore pull request #273
Opened 2023-02-17 05:25 UTC by 18202781743

Add setCachePrefix function to support that cache can be relocated
by caller, It's default value isn't changed, and we can refer to `配置文件规范` in https://github.com/linuxdeepin/deepin-specifications.
  It's permissions need to be considered by caller.
  For DConfig's FileBackend, we use it's default value.

Log: none
Issue: https://github.com/linuxdeepin/dtkcore/issues/271
Influence: none
Change-Id: Ic8407a04f191587627391b64f3c805222a7e2c94

2023-02-17 05:27 UTC, xzl01 reviewed
+1

2023-02-17 05:38 UTC, 18202781743 commented
/review @hillwoodroc

2023-02-17 05:44 UTC, zccrs requested changes

2023-02-17 05:44 UTC, zccrs commented on include/global/dconfigfile.h
> +    virtual void setCachePrefix(const QString &prefix) = 0;
setCachePathPrefix

2023-02-17 05:44 UTC, zccrs commented on tests/ut_dconfigfile.cpp
> +        config.globalCache()->setCachePrefix("configs-global");
这里不应该是指定一个绝对路径吗

2023-02-17 05:44 UTC, zccrs commented on src/dconfigfile.cpp
> +        if (prefix.isEmpty()) {
global级别不应该和user公用一个prefix。接口上最好是灵活一些，允许指定为不同的 prefix

2023-02-17 05:44 UTC, zccrs commented on src/dconfigfile.cpp
>          }
else 时不应该直接使用这个prefix，应该根据  userid 增加一些子路径。setCachePathPrefix 接口的调用方只能指定一个固定的目录，这样会导致 userid 被忽略了，可能多个用户的配置会被放到了一个地方。

2023-02-17 05:50 UTC, 18202781743 commented on src/dconfigfile.cpp
> +        if (prefix.isEmpty()) {
global和user都是 DConfigCache类， 只是DConfigFile::globalCache()获取的是global，DConfigFile::createUserCache()获取的是user的

2023-02-17 05:51 UTC, 18202781743 commented on tests/ut_dconfigfile.cpp
> +        config.globalCache()->setCachePrefix("configs-global");
是可以加上/形成绝对路径
它会跟localPrefix拼接，这里localPrefix是 /tmp/example

2023-02-17 05:56 UTC, 18202781743 commented on src/dconfigfile.cpp
>          }
这个userid应该是调用者添加上去吧，如果根据userid添加子目录，又做了些内部操作，

2023-02-17 07:04 UTC, FeiWang1119 submitted a review, later dismissed

2023-02-21 04:23 UTC, asterwyx requested changes

2023-02-21 04:23 UTC, asterwyx commented on src/dconfigfile.cpp
> +    \a prefix cache's prefix path
这里能不能换成doxygen的写法。

2023-02-21 04:23 UTC, asterwyx commented on src/dconfigfile.cpp
> +    \a prefix cache's prefix path
@param

2023-02-21 05:07 UTC, zccrs requested changes

2023-02-21 05:07 UTC, zccrs commented on src/dconfigfile.cpp
> +    \a prefix cache's prefix path
+1

2023-02-23 06:11 UTC, asterwyx commented
> Add setCachePrefix function to support that cache can be relocated by caller, It's default value isn't changed, and we can refer to `配置文件规范` in https://github.com/linuxdeepin/deepin-specifications. It's permissions need to be considered by caller. For DConfig's FileBackend, we use it's default value.
> 
> Log: none Issue: #271 Influence: none Change-Id: Ic8407a04f191587627391b64f3c805222a7e2c94
Its default value doesn't change.
Caller should consider its permission.

2023-02-23 06:12 UTC, asterwyx commented
> Add setCachePrefix function to support that cache can be relocated by caller, It's default value isn't changed, and we can refer to `配置文件规范` in https://github.com/linuxdeepin/deepin-specifications. It's permissions need to be considered by caller. For DConfig's FileBackend, we use it's default value.
> 
> Log: none Issue: #271 Influence: none Change-Id: Ic8407a04f191587627391b64f3c805222a7e2c94

去掉Change-Id

2023-02-23 06:32 UTC, asterwyx requested changes

2023-02-23 06:32 UTC, asterwyx commented on docs/global/dconfigfile.zh_CN.dox
> +@return
void返回值应该可以不写@return。

2023-02-23 06:32 UTC, asterwyx commented on src/dconfigfile.cpp
> +    @return
这一行是多余的。

2023-03-06 07:51 UTC, zccrs requested changes

2023-03-06 07:51 UTC, zccrs commented on src/dconfigfile.cpp
> +                                                           : DStandardPaths::homePath(isGlobal() ? getuid() : userid);
这里的逻辑为什么有变化，isGloabal() ? getuid()?

2023-03-09 03:39 UTC, 18202781743 commented on src/dconfigfile.cpp
> +                                                           : DStandardPaths::homePath(isGlobal() ? getuid() : userid);
逻辑没有变化，之前是从参数传递过来的，
global的userid变量是个无效值，应该使用当前用户的uid，

2023-03-09 04:58 UTC, zccrs requested changes

2023-03-09 04:58 UTC, zccrs commented on src/dconfigfile.cpp
> +                                                           : DStandardPaths::homePath(isGlobal() ? getuid() : userid);
这样不好理解，还不如保持能传递uid的参数，当uid无效时，fallback到使用this->userid

2023-03-09 10:20 UTC, 18202781743 commented on src/dconfigfile.cpp
> +                                                           : DStandardPaths::homePath(isGlobal() ? getuid() : userid);
之前是静态函数，只能传递参数，改成成员函数了，再传递参数是不是冗余了，
改成成员函数的原因是又增加了cachePrefix这个成员变量的访问，而且是不变的，

2023-03-13 02:26 UTC, asterwyx submitted a review, later dismissed

2023-03-15 02:35 UTC, kegechen reviewed
+1

2023-03-20 06:12 UTC, zccrs requested changes

2023-03-20 06:12 UTC, zccrs commented on src/dconfigfile.cpp
> +                homePath = DStandardPaths::homePath(userid == InvalidUID ? getuid() : userid);
重复的判断

2023-03-20 06:17 UTC, zccrs approved these changes

2023-03-20 06:19 UTC, merged