test: Add unit tests for DStandardPaths
linuxdeepin/dtkcore pull request #279
Opened 2023-02-18 02:42 UTC by ccmywish

Add tests for path(XDG) path(DSG)

Log: Add DStandardPaths tests for path(XDG) and path(DSG)

2023-02-23 02:08 UTC, 18202781743 commented on tests/ut_dstandardpaths.cpp
> +    ASSERT_TRUE( (getenv("XDG_DATA_HOME") == dataHome) || (home + "/.local/share") == dataHome );
看代码逻辑是包括测试fallback时的行为，可以拆开写，主动设置环境变量为空达到fallback的效果，语意明确些，

2023-04-07 09:06 UTC, wineee requested changes

2023-04-07 09:06 UTC, wineee commented on tests/ut_dstandardpaths.cpp
> +    QString datadir = DStandardPaths::path(DStandardPaths::DSG::DataDir);
这里用的不是 DStandardPaths::paths 吗?
DStandardPaths::path 是另一个函数 接受 DStandardPaths::XDG  而不是 DStandardPaths::DSG

2023-04-07 09:19 UTC, closed without merging

2023-04-07 09:23 UTC, wineee commented on tests/ut_dstandardpaths.cpp
> +    QString datadir = DStandardPaths::path(DStandardPaths::DSG::DataDir);
没仔细看，DStandardPaths::path 重载了，会返回 paths 的第一个值，应该是可以用的