chore: Ut error for dci
linuxdeepin/dtkcore pull request #285
Opened 2023-02-23 03:01 UTC by 18202781743

`DDCIFile::list` orders file by numericMode, e.g: 100 sorts after 99.

2023-02-23 06:06 UTC, asterwyx reviewed
+1

2023-02-24 05:12 UTC, zccrs requested changes
dcifile 要保证文件名排序遵守number顺序，UT里的顺序没有问题。

2023-03-03 10:49 UTC, 18202781743 commented
> dcifile 要保证文件名排序遵守number顺序，UT里的顺序没有问题。

"a2.txt", "a11.txt", "b01", "b2"

不是按字符转成ascii比较么，怎么保证2 在11前面， 01又在2前面

2023-03-06 03:15 UTC, zccrs commented
> > dcifile 要保证文件名排序遵守number顺序，UT里的顺序没有问题。
> 
> "a2.txt", "a11.txt", "b01", "b2"
> 
> 不是按字符转成ascii比较么，怎么保证2 在11前面， 01又在2前面

不是按 ascii 比较，标准的描述中已经写明了要求按数字顺序比较。可以用 QCollator 实现

2023-03-09 09:41 UTC, 18202781743 commented
> > > dcifile 要保证文件名排序遵守number顺序，UT里的顺序没有问题。
> > 
> > 
> > "a2.txt", "a11.txt", "b01", "b2"
> > 不是按字符转成ascii比较么，怎么保证2 在11前面， 01又在2前面
> 
> 不是按 ascii 比较，标准的描述中已经写明了要求按数字顺序比较。可以用 QCollator::setNumericMode 实现

代码没有问题，是我本地的环境导致这个ut没过，我用自己编译的qt，使用QCollator::compare返回错误，

2023-03-09 09:41 UTC, closed without merging