fix: Fix incomplete copy of Vtable
linuxdeepin/dtkcore pull request #290
Opened 2023-03-02 04:20 UTC by ComixHe

1. 修复了因不完整拷贝引起的rtti信息丢失的问题
2. 对于虚表结尾判断增加了新的限制条件
3. 增加了调整虚表指针的方法, 后续可以考虑取消对于函数指针和对象指针类型一致的限制

Log: 修复不完整的虚表拷贝

2023-03-02 06:31 UTC, asterwyx reviewed
+1

2023-03-02 07:00 UTC, zccrs commented on include/util/dvtablehook.h
> +                qWarning() << "An error occurred while adjusting this, abort.";
这个log的内容要加更多的描述，不然不对着代码看根本看不懂在警告什么。

2023-03-02 07:02 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    quintptr *new_vtable = new quintptr[vtable_size + 2];
这里额外+2是为了存储什么要在注释里说一下

2023-03-02 07:03 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    memcpy(new_vtable, *obj - 2, vtable_size * sizeof(quintptr));
这里的-2是为了将起始地址定位到什么地方要在注释里解释下

2023-03-02 07:08 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        qDebug() << "error occured :remove original vtable.";
跟上上面的那个评论。这里不用输出日志，可以直接return了，如果觉得没找到是个异常情况，那应该给一个warning

2023-03-02 07:12 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    if (objToOriginalVfptr.find((quintptr **)obj) == objToOriginalVfptr.end())  // Uninitialized memory may have values, for resetVtable
不用专门判断，下面调用remove时就已经包含了判断，如果ret为0，那就等价于找不到。

2023-03-02 07:12 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        qDebug() << "error occured :remove original vtable.";
跟上上面的那个评论。这里不用输出日志，可以直接return了，如果觉得没找到是个异常情况，那应该给一个warning

2023-03-02 07:12 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        qDebug() << "error occured :remove original destructor.";
从代码逻辑来说有没有可能出现 objToOriginalVfptr 中有数据，但是 objDestructFun 中没数据的情况，如果不可能，这里不用输出log，可以直接断言 ret > 0

2023-03-02 07:12 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    std::fill(new_vtable + 2, new_vtable + vtable_size, quintptr(&_DestoryProbe::nothing));
好几个地方在+2，这部分逻辑能集中到一起吗

2023-03-02 07:13 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    *obj = new_vtable + 2;
同上，这里应该是根据虚表的数据，找虚函数的起始位置，多个地方在使用，可以封装到一个函数里处理

2023-03-02 07:14 UTC, zccrs commented on src/util/dvtablehook.cpp
> +            index = i - 2;
同上

2023-03-02 07:14 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    for (int i = 2; i < vtable_size; ++i) {
同上

2023-03-02 07:15 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        {
括号位置不要变

2023-03-02 07:15 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        if (objToGhostVfptr.value((void *)obj) != (*_obj - 2))
同上

2023-03-02 07:18 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    quintptr *vfptr_t2 = (quintptr*)(*_obj)[vtable_size - 1]; // _obj - 2 + vtable_size + 1
这样写很难理解，应该先通过 *_obj 指针获取到真实的虚表起始地址，假设这个值应该是 *_obj - 2，那
auto xxx = *_obj - 2;
vfptr_t2 = xxx[vtable_size + 1];

2023-03-02 07:19 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        qWarning() << "Not override the object virtual table" << obj;
同前面部分对于log的评论。另外建议统一使用 qCWarning

2023-03-02 07:20 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    if (!_obj) {
这里应该是个断言，如果hasVtable的判断能通过，那说明adjustThis在之前使用override时就已经检查通过了，在这里不可能为nullptr

2023-03-02 07:21 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    if (!hasVtable(obj)) {
这些检查跟 resetVptrFun中的重复了吧，那里的是不是不用加了，它总归会调用originalFun

2023-03-02 07:22 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    if (!vfptr_t2) { // double check
前面判断了hasVtable，这里还有可能出现vfptr_t2是nullptr的情况？

2023-03-02 07:22 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    return *(obj - 2) == 0 ? true : false;
在注释里说明下原理

2023-03-02 07:23 UTC, zccrs commented on src/util/dvtablehook.cpp
> +quintptr **DVtableHook::adjustThis(quintptr *obj)
同上，加一些注释

2023-03-02 07:24 UTC, zccrs commented on tests/ut_dvtablehook.cpp
> +    ASSERT_EQ(a->test(0),'b');
逗号后加空格

2023-03-02 07:24 UTC, zccrs commented on tests/ut_dvtablehook.cpp
> +    ASSERT_EQ(a->test(0),'a');
同上，其他地方就不一一指出了

2023-03-02 07:25 UTC, zccrs commented on tests/ut_dvtablehook.cpp
> +        return 'n';
用于区分是哪个lambda函数的话，返回 '1' 和 '2' 是不是更契合

2023-03-02 07:27 UTC, zccrs commented on tests/ut_dvtablehook.cpp
> +    ASSERT_TRUE(DVtableHook::overrideVfptrFun(dynamic_cast<C *>(c1), &C::test, lambda3));
如果 overrideVfptrFun(c1, &A::test, ...)，后续的测试能通过吗？

2023-03-02 07:39 UTC, ComixHe commented on include/util/dvtablehook.h
> +        return begin - *obj + 2; // for offset and rtti info
不是rtti在虚表前面，是rtti在对象中虚表指针指向位置的前面，具体可以看拷贝那里我新画的图示

2023-03-02 07:44 UTC, ComixHe commented on include/util/dvtablehook.h
> +            if ((int64_t)*begin == 0 or (int64_t)*begin < 8)  // offset will grater than 8 bytes(x64)
并不会

2023-03-02 07:45 UTC, zccrs commented on include/util/dvtablehook.h
> +        return begin - *obj + 2; // for offset and rtti info
对就是这个意思，实际上这个提交里我们要确定出一些概念，比如  vtable 是指什么，现在的意思应该是指
RTTI + 虚表 + 其它，如果把它定义为 vtable，“对象中虚表指针指向位置”这个起始地址是 vtable + 2，这个地址也可以有一个定义，比如我们称它为 vfunTable ?

2023-03-02 07:50 UTC, ComixHe commented on include/util/dvtablehook.h
> -        // symbol address + 2 * sizeof(quintptr) = virtal table start address
统一到offsetToTop函数中

2023-03-02 07:55 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    memcpy(new_vtable, *obj - 2, vtable_size * sizeof(quintptr));
统一到adjustToEntry中

2023-03-02 08:03 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    quintptr *new_vtable = new quintptr[vtable_size + 2];
同上

2023-03-02 08:06 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +        qDebug() << "error occured :remove original vtable.";
好像并不是很需要判断，已删除

2023-03-02 08:06 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    if (objToOriginalVfptr.find((quintptr **)obj) == objToOriginalVfptr.end())  // Uninitialized memory may have values, for resetVtable
同上

2023-03-02 08:09 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    std::fill(new_vtable + 2, new_vtable + vtable_size, quintptr(&_DestoryProbe::nothing));
已集中

2023-03-02 08:11 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +            index = i - 2;
这里感觉并不是很好统一，因为这里只是单纯的index,而之前是直接对指针地址进行偏移

2023-03-02 08:11 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    for (int i = 2; i < vtable_size; ++i) {
同上

2023-03-02 08:33 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +        qWarning() << "Not override the object virtual table" << obj;
这里主要是为了防止没有覆盖虚表就reset,所以进行了一个检查，log已更改

2023-03-02 08:36 UTC, ComixHe commented on include/util/dvtablehook.h
> +        return begin - *obj + 2; // for offset and rtti info
这个地址可以叫做VtableEntry,虚函数表的入口，每个对象中都存在一个或多个入口

2023-03-02 09:02 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    if (!hasVtable(obj)) {
这个函数是暴露出去的，为了防止可能的没有reset直接调用originalFun的情况发生

2023-03-02 09:03 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    if (!vfptr_t2) { // double check
已删除

2023-03-03 02:09 UTC, ComixHe commented on tests/ut_dvtablehook.cpp
> +    ASSERT_TRUE(DVtableHook::overrideVfptrFun(dynamic_cast<C *>(c1), &C::test, lambda3));
必须要把类型转换一下,不然模板实例化的时候类型对不上，主要是因为overrideVfptrFun里是用函数指针类型推断对象类型，其实在这里用static_cast也行，因为这两个类型的对象的vtableEntry是相同的

2023-03-03 05:58 UTC, zccrs requested changes

2023-03-03 05:58 UTC, zccrs commented on include/util/dvtablehook.h
> +                QLoggingCategory category{"VtableHook"};
不是这样用的，可以在文件开头处用 Q_LOGGING_CATEGORY 宏定义一个全局的使用，参考dtk其他地方的例子。

2023-03-03 05:58 UTC, zccrs commented on include/util/dvtablehook.h
> +                qCWarning(category, "can't adjust pointer 'This' to correct address, abort.");
Log的内容应该是一个标准的英文段落。一句话的开头要大写，Can't ....
另外警告信息要完成，可以依赖其它日志作为上下文信息辅助理解，但是不能依赖于代码。比如这里应该警告的信息是：“覆盖XXXX对象的XXXX函数失败。XXX类不是Final Class，且调整this指针失败了。” 主要强调的是 override fun 这个行为失败了，无法调整指针是失败的原因。

2023-03-03 05:58 UTC, zccrs commented on include/util/dvtablehook.h
> +                qCWarning(category, "can't adjust pointer 'This' to correct address, abort.");
如果在这一句log的前面或后边会加其它相关的信息，那这里只警告  this 指针调整失败也是可以的，但是目前看这里的log没有其它信息了。

2023-03-03 05:58 UTC, zccrs commented on include/util/dvtablehook.h
> +    static T adjustToEntry(T obj)
Entry和Top分别是指vtable的哪个位置呀？

2023-03-03 05:58 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    if (!hasVtable(obj)) {
我的意思是只在 originalFun 中加检查，因为 resetVfptrFun 肯定会调用它，是不是 resetVfptFun 中就不用再检查了

2023-03-03 06:03 UTC, zccrs requested changes

2023-03-03 06:03 UTC, zccrs commented on src/util/dvtablehook.cpp
> +    if (objToOriginalVfptr.find((quintptr **)obj) == objToOriginalVfptr.end())  // Uninitialized memory may have values, for resetVtable
同什么？

2023-03-03 06:08 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    if (objToOriginalVfptr.find((quintptr **)obj) == objToOriginalVfptr.end())  // Uninitialized memory may have values, for resetVtable
已修改

2023-03-03 06:11 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +    if (!hasVtable(obj)) {
ok,那就统一放到originalFun中

2023-03-03 06:23 UTC, ComixHe commented on include/util/dvtablehook.h
> +    static T adjustToEntry(T obj)
Entry就是对象中vptr指向的地方，从值上来说就是指向Vtable中rtti的后面，Top就是指Vtable和起始地址，在只考虑多继承的情况下就是指向offset_to_top

2023-03-03 06:31 UTC, ComixHe commented on include/util/dvtablehook.h
> +                QLoggingCategory category{"VtableHook"};
已修改

2023-03-03 06:39 UTC, ComixHe commented on include/util/dvtablehook.h
> +                qCWarning(category, "can't adjust pointer 'This' to correct address, abort.");
已修改

2023-03-03 07:25 UTC, zccrs requested changes

2023-03-03 07:25 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        qCWarning(vtableHook,"Failed do override destruct function: %p", obj);
, 后少了空格

2023-03-03 07:25 UTC, zccrs commented on src/util/dvtablehook.cpp
> +        qCWarning(vtableHook,"Failed do override destruct function: %p", obj);
另外可以直接用 qCWaning(vtableHook) << "..." << obj; 的方式输出，这样能额外看到obj的类型等各种信息

2023-03-03 07:25 UTC, zccrs commented on src/util/dvtablehook.cpp
> +                  "Override virtual table failed, the type of target object isn't the last item of inheritance chain and can't adjust pointer "
为什么是 override failed呢，既然 hasVtable 是 true，这说明已经 override 成功了呀

2023-03-03 07:25 UTC, zccrs commented on include/util/dvtablehook.h
> +    static T adjustToEntry(T obj)
加到注释上，从注释中体现出来 top 和 entry 分别是什么地方

2023-03-03 07:25 UTC, zccrs commented on include/util/dvtablehook.h
> +                qCWarning(vtableHook,
可以输出一下对象的地址。

2023-03-03 07:30 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +        qCWarning(vtableHook,"Failed do override destruct function: %p", obj);
已更改

2023-03-03 07:43 UTC, ComixHe commented on src/util/dvtablehook.cpp
> +                  "Override virtual table failed, the type of target object isn't the last item of inheritance chain and can't adjust pointer "
已修改

2023-03-06 03:13 UTC, zccrs approved these changes

2023-03-06 05:09 UTC, merged