feat: append to all appenders when category is not registered
linuxdeepin/dtkcore pull request #294
Opened 2023-03-13 06:30 UTC by ComixHe

Log: 当没有注册对应的category时输出log信息到所有的appender

2023-03-13 07:09 UTC, zccrs requested changes
这个提交要多找几个人本地测试和加分。

2023-03-13 07:09 UTC, zccrs commented on src/log/Logger.cpp
>      // global logger instance also writes all linked categories to the main appenders
相应的注释要改一下，原本的注释是针对于之前的判断条件写的。

2023-03-13 07:10 UTC, zccrs commented
commit message的详情里要说一下这样做的原因是什么。

2023-03-13 07:15 UTC, ComixHe commented on src/log/Logger.cpp
>      // global logger instance also writes all linked categories to the main appenders
ok

2023-03-13 08:49 UTC, kegechen commented on src/log/Logger.cpp
> +        if (!appenders.isEmpty())
反正下面 (`1000行~1002行`) 是要 write 的，这里不需要判断设置 wasWritten 吧。直接删掉就可以吧。
这个意思是，不管 logCategory，全都写到日志中了。

2023-03-13 09:12 UTC, ComixHe commented on src/log/Logger.cpp
> +        if (!appenders.isEmpty())
如果没有找到和category关联的Appender才需要对所有存在的Appendr写入，如果找到了就写对应的Appender,其它的不写

2023-03-14 00:59 UTC, kegechen commented on src/log/Logger.cpp
> +        if (!appenders.isEmpty())
哦，这里的 `appenders` 是 `categoryAppenders`

2023-03-14 05:32 UTC, zccrs commented
/+1

2023-03-14 06:02 UTC, ArchieMeng commented
> 这个提交要多找几个人本地测试和加分。

deepin-terminal本地测试没问题了．

2023-03-14 06:22 UTC, 18202781743 commented on src/log/Logger.cpp
> -    if (logCategory.isNull() || logCategory == d->defaultCategory || linkedToGlobal) {
去掉了linkedToGlobal的判断，logToGlobalInstance是不是就没用了，

2023-03-14 07:01 UTC, ComixHe commented on src/log/Logger.cpp
> -    if (logCategory.isNull() || logCategory == d->defaultCategory || linkedToGlobal) {
应该有用，GlobalInstance可以注册一些公共的Appender,然后有些自定义的需求就创建LocalInstance再注册

2023-03-14 08:44 UTC, ComixHe commented on src/log/Logger.cpp
> -    if (logCategory.isNull() || logCategory == d->defaultCategory || linkedToGlobal) {
无其它函数调用，已废弃

2023-03-14 09:55 UTC, zccrs commented on include/log/Logger.h
> +    QT_DEPRECATED_X("no longer take effect") void logToGlobalInstance(const QString &category, bool logToGlobal = false);
这个接口是不是没有可能被外部调用到，如果是，可以直接删除。

2023-03-14 10:19 UTC, ComixHe commented on include/log/Logger.h
> +    QT_DEPRECATED_X("no longer take effect") void logToGlobalInstance(const QString &category, bool logToGlobal = false);
这个是向外提供的接口，可以直接调用，所以标废弃

2023-03-15 01:32 UTC, zccrs commented
再有一个人+1就可以合入

2023-03-15 08:33 UTC, Decodetalkers approved these changes
+1

2023-03-15 09:21 UTC, zccrs approved these changes

2023-03-15 09:46 UTC, merged