feat: support qt6
linuxdeepin/dtkcore pull request #321
Opened 2023-05-22 07:40 UTC by kegechen

libdtk6core.so
qmake: QT += dtkcore
pkgconfig:  CONFIG += link_pkgconfig  PKGCONFIG += dtk6core cmake: find_package(Dtk6Core) target_link_libraries(${PROJECT_NAME} Dtk6::Core) cmake 注意不要和 Qt5Core 混用， 否则可能出现如下编译报错
The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Core" does not agree with the value of QT_MAJOR_VERSION already determined

2023-06-07 02:21 UTC, kegechen commented on CMakeLists.txt
> +option(ENABLE_QT5 "Enable Qt 5" ON)
CMAKE_PROJECT_VERSION_MAJOR 判断 5还是6可以

2023-06-07 02:52 UTC, kegechen commented on examples/dlog-example/CMakeLists.txt
> +  ${LIBNAME}
那指定是可以的啦

2023-06-07 02:53 UTC, kegechen commented on tools/qdbusxml2cpp/CMakeLists.txt
> +set(BIN_NAME ${TARGET_NAME}${DTK_VERSION_MAJOR})
是的，不然冲突了。需要用这个工具的地方需要从cmake获取到tool的路径运行

2023-06-07 02:55 UTC, kegechen commented on tests/CMakeLists.txt
> +set(TEST_SO_NAME vtabletest${DTK_VERSION_MAJOR})
这个貌似是单元测试中一部分

2023-06-07 02:56 UTC, kegechen commented on cmake/DtkCMake/DtkCMakeConfig.cmake
> +find_package(Dtk6Core REQUIRED)
这个地方应该要用变量。

2023-06-07 05:09 UTC, kegechen commented on CMakeLists.txt
> +    set(QT_VERSION_MAJOR "5")
Qt5_VERSION_MAJOR Qt6_VERSION_MAJOR是有的，QT_VERSION_MAJOR 是我们自己定义的

2023-06-07 05:10 UTC, kegechen commented on misc/DtkCoreConfig.cmake.in
> +include(${CMAKE_CURRENT_LIST_DIR}/Dtk@DTK_VERSION_MAJOR@CoreTargets.cmake)
cmake/Dtk 这个是dtkcommon提供的方便 find_package(Dtk COMPONENTS Core Gui) z和中
Core还是需要分目录

2023-06-07 05:17 UTC, kegechen commented on tools/settings/CMakeLists.txt
>  if(${QT_VERSION_MAJOR} STREQUAL "5")
是的，qt6 没这个 QGSettings

2023-06-07 05:22 UTC, kegechen commented on cmake/DtkCMake/DtkCMakeConfig.cmake
>  add_definitions(-DQ_HOST_NAME=\"${CMAKE_HOST_SYSTEM_PROCESSOR}\")
历史遗留。

2023-06-07 05:27 UTC, kegechen commented on CMakeLists.txt
> +option(ENABLE_QT5 "Enable Qt 5" ON)
还是做成option放着吧。方便cmake随时指定编译不同的的版本，甚至可以同时编译出两种版本，方便自测做适配。
如果跟着CMAKE_PROJECT_VERSION_MAJOR得来回切换传入的值，还没这个灵活。

2023-06-07 05:28 UTC, wineee requested changes

2023-06-07 05:28 UTC, wineee commented on debian/libdtkcore5-bin.install
> +#usr/bin/*
这里为什么加 #

2023-06-07 05:30 UTC, kegechen commented on debian/libdtkcore5-bin.install
> +#usr/bin/*
qdbusxml2cpp-fix 改安装到 DCore/bin 目录下了，不然dtkcore/dtk6core都安装到 /usr/bin/ 文件名也一样会冲突
commit msg有说明

2023-06-07 05:46 UTC, wineee commented on dtkcore.cmake
> +set (TOOL_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/dtk${PROJECT_VERSION_MAJOR}/DCore/bin")
TOOL_INSTALL_DIR 默认 CMAKE_INSTALL _LIBEXECDIR 是不是更好

2023-06-07 06:40 UTC, kegechen commented on dtkcore.cmake
> +set (TOOL_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/dtk${PROJECT_VERSION_MAJOR}/DCore/bin")
在 uos上 CMAKE_INSTALL_LIBDIR  CMAKE_INSTALL_LIBEXECDIR 好像是一样的。

2023-06-12 06:24 UTC, asterwyx commented on dtkcore.cmake
> +set (TOOL_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/dtk${PROJECT_VERSION_MAJOR}/DCore/bin")
在其他发行版上不太一样，红帽系的应该是有区别的

2023-06-12 09:46 UTC, asterwyx commented on cmake/DtkTools/DtkToolsConfig.cmake
> +include("${CMAKE_CURRENT_LIST_DIR}/DtkSettingsToolsMacros.cmake")
下面有.in文件，这里的可以删掉？

2023-06-12 09:46 UTC, asterwyx commented on dtkcore.cmake
> +endmacro()
这个现在是不是没有实际作用了

2023-06-12 13:02 UTC, ComixHe commented on dtkcore.cmake
> +else()
done

2023-06-13 01:34 UTC, kegechen commented on dtkcore.cmake
> +endmacro()
测试代码忘了删了 :+1:

2023-06-13 01:38 UTC, kegechen commented on dtkcore.cmake
> +endmacro()
加一层也没有什么副作用，可以用cmake编译两种版本的dtkcore都在一个build目录下，不至于文件看起来有点混乱

2023-06-13 07:12 UTC, wineee commented on cmake/DtkCMake/DtkCMakeConfig.cmake.in
> +execDeepinOsRelease(--deepin-version DEEPIN_OS_VERSION)
和这个 pr 无关，但是提一下，现在有的应用通过 DEEPIN_OS_VERSION 判断应该使用 23 的接口还是 20 的接口，但是 deepin-os-release 在非 deepin 上无法得到正确的值，编译时使用 -DDEEPIN_OS_VERSION=23 在这里会被覆盖

是不是判断一下 not define 更好？

2023-06-14 09:55 UTC, xzl01 commented on CMakeLists.txt
> -set (DVERSION "5.6.8" CACHE STRING "define project version")
统一使用DTK_VERSION

2023-06-14 10:36 UTC, wineee commented on CMakeLists.txt
> -set (DVERSION "5.6.8" CACHE STRING "define project version")
这个最好还是不要变吧，下游打包还要跟着改

2023-06-15 05:08 UTC, kegechen commented on CMakeLists.txt
> -set (DVERSION "5.6.8" CACHE STRING "define project version")
> 这个最好还是不要变吧，下游打包还要跟着改

跟着改一下吧，DTK_VERSION 更合理

2023-06-15 05:12 UTC, kegechen commented on cmake/DtkCMake/DtkCMakeConfig.cmake.in
> +execDeepinOsRelease(--deepin-version DEEPIN_OS_VERSION)
单独提交一个修复非deepin下被覆盖的问题吧

2023-06-15 05:16 UTC, kegechen commented on .gitignore
> +cmake/*/*.cmake
cmake/DtkCMake/DtkCMakeConfig.cmake.in 会 configurefile 成 cmake/DtkCMake/DtkCMakeConfig.cmake 或者 cmake/DtkCMake/Dtk6CMakeConfig.cmake 主要是不想生成的文件出现在git变动，那还是修改生成目录到 CMAKE_CURRENT_BINARY_DIR 吧

2023-06-15 07:09 UTC, kegechen commented on debian/libdtkcore5-bin.install
> +usr/*/*/DCore/bin/*
`/usr/libexec/dtk5/DCore/bin/*`

2023-06-15 08:14 UTC, asterwyx approved these changes

2023-06-15 10:17 UTC, asterwyx commented
+1

2023-06-15 10:29 UTC, ComixHe approved these changes
+1

2023-06-16 00:32 UTC, merged