fix(dccinterface): fix cannot get the right type
linuxdeepin/dtkcore pull request #326
Opened 2023-05-26 08:19 UTC by Decodetalkers

Log: fix cannot get the right type

2023-05-26 08:33 UTC, 18202781743 commented
+1

2023-05-26 09:35 UTC, zccrs requested changes
针对这种情况加一个单元测试

2023-05-28 08:25 UTC, ComixHe commented
+1 建议在代码中添加一些注释来说明为什么要这么做

2023-05-29 07:52 UTC, 18202781743 commented on tests/ut_ddbusinterface.cpp
> +        m_parent = new QObject();
这个m_parent好像没用到呀，

2023-05-29 07:52 UTC, 18202781743 commented on tests/ut_ddbusinterface.cpp
> +// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
2023

2023-05-29 07:56 UTC, Decodetalkers commented on tests/ut_ddbusinterface.cpp
> +        m_parent = new QObject();
哦，忘记了

2023-05-29 08:05 UTC, 18202781743 approved these changes

2023-05-30 06:09 UTC, zccrs requested changes

2023-05-30 06:09 UTC, zccrs commented on tests/ut_ddbusinterface.cpp
> +    EXPECT_EQ(m_testDBusInterfaceParent->objectpaths().length(), objectpaths.length());
为什么是从 m_testDBusInterfaceParent 而不是 m_testInterface 中读取这个属性呢

2023-05-30 06:09 UTC, zccrs commented on tests/fakedbus/fakedbusservice.h
> +    Q_PROPERTY(QString strproperty READ strproperty)
用驼峰命名

2023-05-30 06:09 UTC, zccrs commented on tests/fakedbus/fakedbusservice.h
> +    Q_PROPERTY(QList<QDBusObjectPath> objectpaths READ objectpaths);
同上

2023-05-30 06:09 UTC, zccrs commented on tests/ut_ddbusinterface.cpp
> +TEST_F(ut_DDBusInterface, TestProperty)
这个test能体现出对 QDBusArgument 类型的测试吗，没看出来

2023-05-31 07:42 UTC, zccrs commented on tests/ut_ddbusinterface.cpp
> +TEST_F(ut_DDBusInterface, TestProperty)
QList<QDBusObjectPath>会被包装成 QDBusArgument 类型

2023-05-31 07:44 UTC, zccrs approved these changes

2023-05-31 07:45 UTC, Decodetalkers commented
/merge

2023-05-31 07:46 UTC, merged