fix: DTextEncoding ut failed in Qt6.
linuxdeepin/dtkcore pull request #332
Opened 2023-06-07 06:47 UTC by rb-union

1. Fix DTextEncoding muti-byte encoding calculation error.
2. Replace QTextCodec with QStringConverter in Qt6 env.
3. Add convertedBytes param in the convertTextEncodinig() interface.

Log: Fix DTextEncoding ut failed in Qt6.

2023-06-07 06:54 UTC, rb-union commented
/review @kegechen  @18202781743  @asterwyx @FeiWang1119

2023-06-07 09:07 UTC, kegechen commented on tests/ut_dtextencoding.cpp
>  QString ut_DTextEncoding::tmpFileName = QString("/tmp/ut_DTextEncoding_temp.txt");
这些文件能不能用 QTemporaryFile

2023-06-07 09:37 UTC, kegechen requested changes

2023-06-07 09:37 UTC, kegechen commented on include/util/dtextencoding.h
> +                                    int *convertedBytes = nullptr);
新加一个接口吧，尽量保证发出去的接口不动.

2023-06-08 02:19 UTC, rb-union commented on include/util/dtextencoding.h
> +                                    int *convertedBytes = nullptr);
调整为新增接口，旧版接口保留。

2023-06-08 02:21 UTC, rb-union commented on tests/ut_dtextencoding.cpp
>  QString ut_DTextEncoding::tmpFileName = QString("/tmp/ut_DTextEncoding_temp.txt");
tmpFileName的调用已调整为 QTemporaryFile，不过最后的两组用例初始状态需保证移除文件，所以未使用QTemporaryFile。

2023-06-08 06:00 UTC, kegechen commented on src/util/dtextencoding.cpp
> +        return 0 == convertError;
if else 都return了。
376行的 return true; will never be executed 警告。

2023-06-08 06:09 UTC, kegechen approved these changes

2023-06-08 09:26 UTC, merged

2023-06-09 07:38 UTC, rb-union commented on src/util/dtextencoding.cpp
> +        return 0 == convertError;
遗漏项已单独PR