feat: add DThreadUtils class
linuxdeepin/dtkcore pull request #334
Opened 2023-06-12 05:43 UTC by ComixHe

Log: 添加DThreadUtils类

2023-06-12 06:06 UTC, kegechen commented
可以更新一个doc, 将使用的代码片段放里面

2023-06-12 06:07 UTC, ComixHe commented
> 可以更新一个doc, 将使用的代码片段放里面

@zccrs

2023-06-14 09:02 UTC, zccrs requested changes

2023-06-14 09:02 UTC, zccrs commented on include/util/dthreadutils.h
> +};
It is end of class DThreadUtils?

2023-06-14 10:10 UTC, ComixHe commented on include/util/dthreadutils.h
> +class LIBDTKCORESHARED_EXPORT D_DECL_DEPRECATED_X("Deprecated after Qt5") FunctionCallProxy : public QObject
ok

2023-06-14 10:10 UTC, ComixHe commented on include/util/dthreadutils.h
> +};
yes

2023-06-14 10:11 UTC, ComixHe commented on include/util/dthreadutils.h
> +};
end of namespace DThreadUtil.

2023-06-15 02:01 UTC, zccrs commented on include/util/dthreadutils.h
> +};
no `;` for namespace

2023-06-15 05:53 UTC, zccrs requested changes

2023-06-15 05:53 UTC, zccrs commented on include/util/dthreadutils.h
> +
remove

2023-06-15 05:53 UTC, zccrs commented on include/util/dthreadutils.h
> +    friend class Caller;
???

2023-06-15 05:53 UTC, zccrs commented on include/util/dthreadutils.h
> +    -> decltype(fun(args...))
Don't change anything of old codes.

2023-06-15 05:53 UTC, zccrs commented on include/util/dthreadutils.h
> +
remove

2023-06-15 05:53 UTC, zccrs commented on include/util/dthreadutils.h
> +#endif
???

2023-06-15 05:53 UTC, zccrs commented on src/util/dthreadutils.cpp
> +
remove

2023-06-15 05:53 UTC, zccrs commented on src/util/util.cmake
> +  list(REMOVE_ITEM UTILS_SOURCE "${CMAKE_CURRENT_LIST_DIR}/dtimeloop.cpp")
And DAsync

2023-06-15 05:53 UTC, zccrs commented on tests/CMakeLists.txt
> +  list(REMOVE_ITEM TEST_SOURCE "${CMAKE_CURRENT_LIST_DIR}/ut-dthreadutils.cpp") //TODO: wait for complate
Finish this work in this commit.

2023-06-16 01:48 UTC, zccrs requested changes

2023-06-16 01:48 UTC, zccrs commented on include/util/dthreadutils.h
> +    inline auto call(QObject *context, Func fun, Args &&...args) const
remove `inline`

2023-06-16 01:48 UTC, zccrs commented on include/util/dthreadutils.h
> +    class CallEvent : public AbstractCallEvent
add `Q_DECL_HIDDEN`

2023-06-16 01:48 UTC, zccrs commented on include/util/dthreadutils.h
> +class DThreadUtils final
`LIBDTKCORESHARED_EXPORT`

2023-06-16 05:02 UTC, zccrs requested changes

2023-06-16 05:02 UTC, zccrs commented on docs/util/dthreadutils.zh_CN.dox
> +@details 主要用来进行异步线程调用
在类的介绍中还要说一下，DThreadUtils 的所有 public 接口都是线程安全的

2023-06-16 05:05 UTC, zccrs requested changes

2023-06-16 05:05 UTC, zccrs commented on docs/util/dthreadutils.zh_CN.dox
> +@brief 在对应的线程执行传入的成员函数, 阻塞
这里要特别说一下，调用者自己要确保对应线程有事件循环，否则会无限等待。

2023-06-16 06:13 UTC, zccrs approved these changes

2023-06-16 06:15 UTC, merged