chore: Implement DSGApplication::getId
linuxdeepin/dtkcore pull request #389
Opened 2023-10-26 02:52 UTC by kegechen

Get appid from dde-application-manager
Also available in the linglong box due to using pidfd

2023-10-26 03:38 UTC, black-desk commented on src/dsgapplication.cpp
> +    QDBusReply<QString> reply = infc.call("Identify", QVariant::fromValue(QDBusUnixFileDescriptor(pidfd)));
reply里面不是qstring

https://github.com/linuxdeepin/dde-application-manager/blob/e6cd2c5df1d53ad1472e648a386862adc789681e/api/dbus/org.desktopspec.ApplicationManager1.xml#L17-L19

2023-10-26 03:38 UTC, zccrs requested changes

2023-10-26 03:38 UTC, zccrs commented on src/dsgapplication.cpp
> +    static QMap<qint64, QByteArray> pid2Appid;
这里不要做cache，因为这里没法知道这个 pid 是不是脏的，有可能先前记录的程序已经退出了，现在的pid是个后来又启动的新程序。如果需要做cache，可以让调用者自己做。
另外，最多被使用的情况应该是查找自己的 application id，这种需求可以由AM加个单独的接口，在 DSGApplication中也提供个单独的接口，在这个接口中就可以cache获取到的值了，因为自己的 application id 是不可能发生变化的。

2023-10-26 03:38 UTC, zccrs commented on src/dsgapplication.cpp
> +        qWarning() << "Identify from AM failed." << reply.error().message();
qCWarning

2023-10-26 03:38 UTC, zccrs commented on src/dsgapplication.cpp
> +QByteArray DSGApplication::escape2ObjectPath(const QByteArray &appid)
这是要干啥，为什么还需要做加工？

2023-10-26 03:39 UTC, black-desk commented on src/dsgapplication.cpp
> +    static QMap<qint64, QByteArray> pid2Appid;
而且这地方做了缓存以后好像没有释放

2023-10-26 03:41 UTC, black-desk commented on src/dsgapplication.cpp
> +QByteArray DSGApplication::escape2ObjectPath(const QByteArray &appid)
是之前说的 如果你拿着一个appid, 想要找am对应的object, 那么你需要把appid里面 作为dbuspath不合法的部分escape掉.

2023-10-26 03:43 UTC, black-desk commented on src/dsgapplication.cpp
> +        close(pidfd);
可能不需要close, 当你下面构造出QDBusUnixFileDescriptor 的时候, 这个fd的所有权就已经转交了.

2023-10-26 05:29 UTC, kegechen commented on src/dsgapplication.cpp
> +        close(pidfd);
我看手册提供的demo是要close的。

2023-10-26 05:32 UTC, kegechen commented on src/dsgapplication.cpp
> +    QDBusReply<QString> reply = infc.call("Identify", QVariant::fromValue(QDBusUnixFileDescriptor(pidfd)));
我这里只关心 QString , 结果也确实是QString  `"Unexpected reply signature: got \"s\" (QString), expected \"xxx\" (xxx)"`
不过可以从 QDBusMessage 中的 arguments 分离出来三个结果。

2023-10-26 05:34 UTC, kegechen commented on src/dsgapplication.cpp
> +QByteArray DSGApplication::escape2ObjectPath(const QByteArray &appid)
appid 转成 am的 dbuspath 部分的接口。目前貌似只有 https://github.com/linuxdeepin/dde-launchpad/blob/2874d61a46cfdc15d2276d4a69b1c36d5d1b7959/src/ddeintegration/appmgr.cpp#L35 这个在用

2023-10-26 07:33 UTC, kegechen commented on src/dsgapplication.cpp
> +QByteArray DSGApplication::escape2ObjectPath(const QByteArray &appid)
https://github.com/linuxdeepin/dtkcore/pull/390 这里做了，就不再 dsgapplication 中加了

2023-10-27 01:48 UTC, BLumia reviewed
PR描述里写了两个特性但代码变更/commit里只有一个，是漏了还是打算拆开分开提PR？

2023-10-27 07:17 UTC, kegechen commented
> PR描述里写了两个特性但代码变更/commit里只有一个，是漏了还是打算拆开分开提PR？

折叠的评论里面说了「pull-390 这里做了，就不再 dsgapplication 中加了」

2023-10-30 05:44 UTC, 18202781743 approved these changes

2023-10-30 05:56 UTC, zccrs approved these changes

2023-10-30 06:05 UTC, merged