chore: add dtk dbusscanner
linuxdeepin/dtkcore pull request #392
Opened 2023-11-13 10:24 UTC by Decodetalkers

Log:

2023-11-13 10:24 UTC, Decodetalkers commented
从qt那边偷了过来

2023-11-14 01:30 UTC, 18202781743 commented on cmake/DtkTools/DtkDBusMacorsQt5.cmake
> +function(dtk_add_dbus_interface_qt5 _sources _interface _basename)
这个qt5的后缀可以去掉，或者封装一个给外部调用的没有后缀的？

2023-11-14 01:30 UTC, 18202781743 commented on cmake/DtkTools/DtkToolsConfig.cmake.in
> +set(DTK_VERSION_MAJOR @DTK_VERSION_MAJOR@)
这个可以不导出，即使导出也不在这里，

2023-11-14 01:30 UTC, 18202781743 commented on cmake/DtkTools/DtkToolsConfig.cmake.in
> +if("${DTK_VERSION_MAJOR}" STREQUAL "6")
这个直接拼字符串来获得文件名？

2023-11-14 01:30 UTC, 18202781743 commented on dtkcore.cmake
> +  install(FILES cmake/DtkTools/DtkDBusMacorsQt6.cmake
文件名Dtk6DBusMacros？

2023-11-14 02:00 UTC, kegechen commented
> 从qt那边偷了过来

借鉴，「读书人的事能算偷么？」

2023-11-14 02:35 UTC, asterwyx requested changes

2023-11-14 02:35 UTC, asterwyx commented on dtkcore.cmake
> +
这里感觉也可以使用字符串拼接的方式拿到要安装的文件名，这样的话，如果有除了5和6之外的版本还能在安装阶段提前报错。

2023-11-14 02:35 UTC, asterwyx commented on cmake/DtkTools/Dtk6DBusMacors.cmake
这两个文件虽然不能够完全复用，但是应该有一部分逻辑可以提取出来复用，可以提取出来的尽量提取出来。

2023-11-16 03:35 UTC, BLumia commented on dtkcore.cmake
> +        DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/Dtk${DTK_VERSION_MAJOR}Tools")
没改干净

2023-11-16 03:35 UTC, BLumia commented on dtkcore.cmake
> +        DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/Dtk${DTK_VERSION_MAJOR}Tools")
哦我看错了，nevermind（（

2023-11-16 03:40 UTC, BLumia commented on LICENSES/BSD-3-Clause.txt
> +Copyright (c) 2017 - 2022 UnionTech Software Technology Co., Ltd.
这个是 `reuse download --all` 下下来的许可？看着不像啊（（

2023-11-16 03:41 UTC, Decodetalkers commented on LICENSES/BSD-3-Clause.txt
> +Copyright (c) 2017 - 2022 UnionTech Software Technology Co., Ltd.
这里不应该写吗。我想得是这个原来是从qt抄来的，所以要标记bsd

2023-11-16 07:36 UTC, asterwyx requested changes
Macor -> Macro

2023-11-16 07:38 UTC, asterwyx approved these changes

2023-11-16 07:42 UTC, Decodetalkers commented
/check obs

2023-11-16 07:44 UTC, Zeno-sole commented
/retest

2023-11-16 07:48 UTC, Zeno-sole commented
/check obs

2023-11-16 08:11 UTC, asterwyx commented
/approve

2023-11-17 01:30 UTC, kegechen commented
/merge

2023-11-17 01:30 UTC, kegechen approved these changes

2023-11-17 01:33 UTC, Decodetalkers commented
/merge

2023-11-17 01:34 UTC, 18202781743 commented
/approve

2023-11-17 01:35 UTC, 18202781743 commented
/+1

2023-11-17 01:37 UTC, merged