feat: allow skip including headers of annootations
linuxdeepin/dtkcore pull request #394
Opened 2023-11-24 03:40 UTC by Decodetalkers

Log:
Issue: https://github.com/linuxdeepin/dtk/issues/147

2023-11-28 01:51 UTC, asterwyx commented
commit message里面有typo

2023-12-04 07:36 UTC, kegechen commented
/+1

2023-12-08 06:43 UTC, 18202781743 commented on tools/qdbusxml2cpp/qdbusxml2cpp.cpp
> +    if (!skipIncludeAnnotations) {
看下面还有对annotations进行处理的逻辑，是不是需要一起跳过，
![image](https://github.com/linuxdeepin/dtkcore/assets/20967670/24d08163-60d5-4757-96ed-9e42476b6190)

2023-12-08 08:38 UTC, 18202781743 commented on tools/qdbusxml2cpp/qdbusxml2cpp.cpp
> +    if (!skipIncludeAnnotations) {
include都跳过了，类型处理不跳过么？

2023-12-08 08:40 UTC, Decodetalkers commented on tools/qdbusxml2cpp/qdbusxml2cpp.cpp
> +    if (!skipIncludeAnnotations) {
qt的工具是要求所有类型都放在-I的头文件的，我们为了方便把类型分开成各个头文件了

2023-12-08 08:47 UTC, 18202781743 approved these changes

2023-12-11 03:25 UTC, zccrs requested changes
这个命名可以改一下，其它没有问题

2023-12-11 03:25 UTC, zccrs commented on cmake/DtkTools/DtkDBusMacros.cmake
> +    get_source_file_property(_skipincludeannotations ${_interface} SKIP_INCLUDEANNOTATIONS)
`SKIP_INCLUDE_ANNOTATIONS`

2023-12-14 05:40 UTC, asterwyx commented
如果想要应用新的workflow文件，需要重新force-push一下，等workflow准备好之后force-push一下吧

2023-12-14 07:33 UTC, Decodetalkers commented
@zccrs 已经改好了

2023-12-18 01:51 UTC, zccrs approved these changes

2023-12-19 06:33 UTC, merged