feat: support to set appId for DConfig
linuxdeepin/dtkcore pull request #404
Opened 2024-02-28 10:15 UTC by 18202781743

It's useful for generic config to clearly specify application id.

2024-02-29 05:31 UTC, asterwyx commented on src/dconfig.cpp
> + * \brief Clearly specify application Id for config.
```suggestion
 * \brief Explicitly specify application Id for config.
```

2024-02-29 05:46 UTC, zccrs requested changes

2024-02-29 05:46 UTC, zccrs commented on docs/global/dconfig.zh_CN.dox
> +@brief 明确指定应用Id,不采用默认的appId
“默认的appId”是啥不好理解，可以明确说是 DSGApplication 里的

2024-02-29 05:46 UTC, zccrs commented on src/dconfig.cpp
> +    _globalAppId = appId;
最好判断下 _globalAppId 是不是已经有值，如果有了，要给个警告，因为一般来说不应该重复设置

2024-03-01 05:29 UTC, kegechen approved these changes

2024-03-05 03:30 UTC, zccrs approved these changes

2024-03-05 03:46 UTC, merged