Loggingrules dconfig support (cherry-pick from gerrit)
linuxdeepin/dtkcore pull request #413
Opened 2024-05-09 09:50 UTC by kegechen

-  允许基于dtk开发的应用动态控制其日志输出等级 
-  lshw查询内存大小时返回多元素数组,修正解析过程
- 从文件中读取deepinType和productType值时因为权限问题会失败
- 增加registerLoggingRulesWatcher接口
- 修复计算 build 版本号错误的问题 
- 修复日志格式时间戳显示异常问题

2024-05-09 09:56 UTC, kegechen commented
@Whale107 @Groveer @993381

2024-05-10 01:20 UTC, Groveer approved these changes

2024-05-10 01:42 UTC, 18202781743 commented on src/log/LogManager.cpp
> +    QByteArray logRules = qgetenv("QT_LOGGING_RULES");
这个如果设置的话, 也是在dconfig有效的时候设置吧,
用户不能通过QT_LOGGING_RULES去设置日志等级么,

2024-05-10 01:42 UTC, 18202781743 commented on include/log/LogManager.h
> +     * 此方法应该在创建 QApplication 之前调用，否则 QT_LOGGING_RULES 环境变量会覆盖 dconfig 的的值
必须QApplication前调用么? AppId 如果从 DSGApplication::id获取, 它可能需要访问QCoreApplication, 不知道会不会有影响,

2024-05-10 01:42 UTC, 18202781743 commented on src/dsysinfo.cpp
> -    if (productType >= 0 && !inTest()) {
0枚举为DSysInfo::UnknownType

2024-05-10 02:05 UTC, kegechen commented on src/log/LogManager.cpp
> +    QByteArray logRules = qgetenv("QT_LOGGING_RULES");
下面虽然 unset 了，但是还是调用了 QLoggingCategory::setFilterRules

2024-05-10 07:46 UTC, kegechen commented on src/dsysinfo.cpp
> -    if (productType >= 0 && !inTest()) {
默认-1， 失败后 0（unknown）想要失败了之后再次 ensureReleaseInfo，

2024-05-10 08:05 UTC, zccrs requested changes

2024-05-10 08:05 UTC, zccrs commented on src/log/LogManager.cpp
> +    qunsetenv("QT_LOGGING_RULES");
不能这样处理，要保持环境变量的优先级。如果应用程序期望 DLogManager 遵循里的设置，那就不要自己设置环境变量。

2024-05-10 08:05 UTC, zccrs commented on src/log/LogManager.cpp
> +        appId = DSGApplication::id();
不这样处理，这俩个appid都保留，如果都不是空，且不相等，分别为他们创建 DConfig 对象。如果 D_LOG_APP_ID 中能读取到 rules ，那就优先用这个值，否则用 DSGApplication::id 获取到的值。

2024-05-10 08:09 UTC, zccrs commented on src/log/LogManager.cpp
> +    if (appId.isEmpty()) {
可以提供环境变量来禁用。等以后重整 log 相关的类之后再考虑标准接口。

2024-05-10 08:11 UTC, kegechen commented on src/log/LogManager.cpp
> +    qunsetenv("QT_LOGGING_RULES");
专业版给这个 `/etc/X11/Xsession.d/00deepin-dde-env` 里面默认加了一个 `QT_LOGGING_RULES="*.debug=false"
`
那么 `QLoggingCategory::setFilterRules` 会被忽略

2024-05-10 08:26 UTC, zccrs commented on src/log/LogManager.cpp
> +    qunsetenv("QT_LOGGING_RULES");
那专业版自己解决，搞不懂为什么要加这个

2024-05-10 09:17 UTC, kegechen commented on src/log/LogManager.cpp
> +        appId = DSGApplication::id();
- D_LOG_APP_ID 非空，且读到的 rules 非空，就用这个配置
- D_LOG_APP_ID 配置读取失败，再使用 DSGApplication::id 读配置

不去判断二者是否相等，

2024-05-11 01:40 UTC, zccrs requested changes

2024-05-11 01:40 UTC, zccrs commented on src/log/LogManager.cpp
> +    if (!m_loggingRulesConfig && !appId.isEmpty() && appId != dsgAppId)
这个 m_loggingRulesConfig 在这里不可能是 nullptr, 如果它是 nullptr，那后续再创建 createDConfig(dsgAppId) 也会是 nullptr。所以，这个判断会导致只要指定了 DTK_LOGGING_APP_ID，那总会使用它。这不是我们想要的效果，可以把 DTK_LOGGING_APP_ID 改成  DTK_LOGGING_FALLBACK_APP_ID，在这里不用判断什么，这两个 id 的 DConfig 全都创建，然后用 DConfig::isDefaultValue(RULES_KEY) 判断值是否设置，按优先级来，谁设置了就优先用谁。dsgAppId 的优先级最高，DTK_LOGGING_FALLBACK_APP_ID 的第二。

2024-05-11 06:12 UTC, kegechen commented on src/log/LogManager.cpp
> +    if (!m_loggingRulesConfig && !appId.isEmpty() && appId != dsgAppId)
初始化可以这么选优先级，那么valuechanged这里两个id（假设不相同） dconfig 的都监听？ 搞得有点复杂

2024-05-13 03:28 UTC, zccrs requested changes

2024-05-13 03:28 UTC, zccrs commented on src/log/LogManager.cpp
> +    DConfig * m_dsgConfig = nullptr;
用作用域指针

2024-05-13 03:28 UTC, zccrs commented on src/log/LogManager.cpp
> +    QObject::connect(fallbackConfig, &DConfig::valueChanged, fallbackConfig, [=](const QString &key){
这里的 fallbackConfig 不是 nullptr 吗？

2024-05-13 03:28 UTC, zccrs commented on src/log/LogManager.cpp
> +        updateLoggingRules(dsgConfig);
不用捕获变量，直接用 QObject::sender()

2024-05-13 03:28 UTC, zccrs commented on src/log/LogManager.cpp
> +        QObject::connect(fallbackConfig, &DConfig::valueChanged, fallbackConfig, [=](const QString &key){
代码格式。

2024-05-13 03:28 UTC, zccrs commented on src/log/LogManager.cpp
> +    QObject::connect(fallbackConfig, &DConfig::valueChanged, fallbackConfig, [=](const QString &key){
代码格式

2024-05-13 03:28 UTC, zccrs commented on src/log/LogManager.cpp
> +            if (dsgConfig && !dsgConfig->isDefaultValue(RULES_KEY)) {
此时这个 dsgConfig 可能已经被销毁了。因为这是捕获到的变量，只要一开始不是 nullptr，那永远都不会是 nullptr。建议用 this->m_dsgConfig。

2024-05-13 03:28 UTC, zccrs commented on src/log/LogManager.cpp
> +    if (isDsgCached) {
直接把这部分的逻辑抽成一个函数使用，两个 DConfig 的 valueChanged 信号都连接它去处理。

2024-05-14 01:49 UTC, kegechen commented on src/log/LogManager.cpp
> +    QObject::connect(fallbackConfig, &DConfig::valueChanged, fallbackConfig, [=](const QString &key){
写错了。。

2024-05-14 05:05 UTC, kegechen commented on src/log/LogManager.cpp
> +        updateLoggingRules(dsgConfig);
'sender' is a protected member of 'QObject'

2024-05-14 09:24 UTC, zccrs approved these changes

2024-05-14 09:34 UTC, 18202781743 commented on src/log/LogManager.cpp
> +void DLogManagerPrivate::updateLoggingRules()
不能在应用不重启的情况下,重置之前设置的值了,

2024-05-17 01:55 UTC, kegechen commented on src/log/LogManager.cpp
> +void DLogManagerPrivate::updateLoggingRules()
似的，reset 之后，isDefaultValue 是 true，也就是说不能用reset的方式来清空rules，只能删除的方式清空

2024-05-17 01:56 UTC, merged