fix: crashed when access DSGApplication::id early
linuxdeepin/dtkcore pull request #418
Opened 2024-05-17 08:00 UTC by 18202781743

Add fallback, using fileName of /proc/self/exe as AppId.
Remove assert for empty appId.

2024-05-17 08:01 UTC, 18202781743 commented
https://github.com/linuxdeepin/dde-application-manager/pull/211

2024-05-17 08:32 UTC, zccrs requested changes

2024-05-17 08:32 UTC, zccrs commented on src/dsgapplication.cpp
> +                result = selfFile.fileName().toLocal8Bit();
用绝对路径来，因为有些可执行文件可能路径不同，但是文件名相同

2024-05-17 08:32 UTC, zccrs commented on src/dsgapplication.cpp
> +            QFileInfo selfFile(QFile::symLinkTarget("/proc/self/exe"));
在这之前先尝试使用 /proc/self/cmdline 里的执行命令。

2024-05-17 09:52 UTC, zccrs requested changes

2024-05-17 09:52 UTC, zccrs commented on src/dsgapplication.cpp
> +    QString format(QString::fromStdString(appId.toStdString()));
为什么要转成std string呢，用 fromLocal8Bit() 就行

2024-05-17 09:52 UTC, zccrs commented on src/dsgapplication.cpp
> +                result = file.readLine();
要去掉 cmdline 里的参数，只保留命令文件的路径

2024-05-17 09:52 UTC, zccrs commented on src/dsgapplication.cpp
> +                result = file.fileName().toLocal8Bit();
需要这个文件的绝对路径，可以用 QFileInfo。

2024-05-17 09:55 UTC, 18202781743 commented on src/dsgapplication.cpp
> +    QString format(QString::fromStdString(appId.toStdString()));
这样字会丢失字符, 因为中间有\0字符,

2024-05-17 09:55 UTC, zccrs requested changes

2024-05-17 09:55 UTC, zccrs commented on src/dsgapplication.cpp
> +                result = file.readLine();
第一行就是文件路径对吧？行尾有换行符吗，有的话可能需要移除

2024-05-20 08:03 UTC, kegechen submitted a review, later dismissed

2024-05-21 01:31 UTC, zccrs approved these changes

2024-05-21 02:13 UTC, merged