feat: add Gentoo for DSysInfo
linuxdeepin/dtkcore pull request #63
Opened 2022-05-18 05:49 UTC by Rabenda

Signed-off-by: Han Gao <gaohan@deepin.org>

2022-05-19 13:50 UTC, justforlxz requested changes

2022-05-19 13:53 UTC, Rabenda commented on src/dsysinfo.h
> +        Gentoo,
已修改

2022-05-19 14:17 UTC, justforlxz approved these changes

2022-05-30 05:55 UTC, 993381 commented
/check

2022-05-31 06:21 UTC, kegechen commented on src/dsysinfo.h
> +        Gentoo,
commit信息里面要加上一个Log, 类似下面的

feat: xxxx

xxxx

Log: add Gentoo
Influence: dsysinfo

2022-06-24 02:26 UTC, BLumia commented
奇怪，我记得没有对没加入 linuxdeepin 组织的贡献者加 `Log:` 字段的约束来着。目前可以先 amend 一下 commit 信息，需要在 `Signed-off-by:` 上面加一行 `Log:` （后面可以是空的）。后续我把这个检查改一下。

2022-07-18 09:17 UTC, zccrs approved these changes

2022-07-18 09:18 UTC, merged