feat: add the permission management for files
linuxdeepin/dtkcore pull request #78
Opened 2022-07-26 07:08 UTC by cccccccb

Use DCapManager class to unify privilege management on
whether to open files or not.

By registering a special file engine, the scope of action
after registration is global unless called the unregister
function manually.

By default, the application can still access some directories
and files with permissions after it is started, but when it
access files beyond the scope of these directories, it will
not get any information.

The default directory includes: Home path; Cache path; DSG path
XDG path etc.

Log:
Influence: null
Change-Id: I0fed6051addc56001b382fc34f73b046c0e4aca2

2022-07-28 06:35 UTC, ssk-wh requested changes
dcapfsfileengine.cpp line 36 考虑下如果应用传递的路径就是/会不会有问题
dcapmanager.cpp line 44 和line 47 条件可以进行合并
dcapmanager.cpp line 67 68 这里为什么要多这一步呀
dcapmanager.cpp line 116 如果addPath时是“/tmp/test/”,removePath时是"/tmp/test"，可以remove掉吗

2022-08-02 02:19 UTC, kegechen commented
根据原设计应该不能影响整个进程，还是得新加一个dcapfile类似的东西，通过setfileengine来实现管控。

2022-08-11 03:43 UTC, cccccccb commented
后续根据以下方式修改本提交：

-  1. 使用方直接使用一个类似 DCapFile 的类代替 QFile 进行文件读写，直接使用 DCapFile 类时，默认强制使用目录的权限管理
-  2. 提供一种 override 掉 QFile 的全局 File Engine，使用方可以主动调用接口使用 DTK 提供的这个 File Engine，使用方在使用该接口后，无论使用 DCapFile 或是 QFile 都将强制使用目录的权限管理。这种方式下，使用全局权限进行目录管理，即所有使用到 QFile 和 QDir 的代码，都默认进行了权限管理。

2022-08-12 07:08 UTC, cccccccb commented
上述问题已解决 @ssk-wh @kegechen , 帮忙再审阅一下

2022-08-12 07:08 UTC, cccccccb commented
/review @zccrs

2022-08-12 09:23 UTC, cccccccb commented
/check check_job/build

2022-08-12 09:35 UTC, cccccccb commented
/check check_job/build

2022-08-12 09:48 UTC, cccccccb commented
/check check_job/build

2022-08-15 07:18 UTC, kegechen commented on src/filesystem/dcapfile.h
> +* along with this program.  If not, see <http://www.gnu.org/licenses/>.
按照新的 license 规范修改，reuse

2022-08-15 07:28 UTC, kegechen commented on src/filesystem/dcapmanager.cpp
> +    bool ret = path.contains(directoryPath);
contains 容易构造出错误情况
path:  /tmp/usr/share/
check: /usr/share

2022-08-15 07:39 UTC, kegechen requested changes
ut文件名改一下。

2022-08-15 09:54 UTC, cccccccb commented on src/filesystem/dcapmanager.cpp
> +    bool ret = path.contains(directoryPath);
已修改

2022-08-16 01:08 UTC, cccccccb commented
/check check_job/build

2022-08-26 03:43 UTC, kegechen approved these changes

2022-08-26 03:45 UTC, merged