Fix: link to dl
linuxdeepin/dtkcore pull request #82
Opened 2022-08-09 14:04 UTC by hillwoodroc

It should link to dl for some distrbutions. For example, openSUSE.
The compiling won't be success without this link.

log:

2022-08-10 08:29 UTC, Decodetalkers commented
请问这个libdl.so来自哪个包呢

2022-08-11 03:28 UTC, hillwoodroc commented
> 请问这个libdl.so来自哪个包呢

glibc

2022-08-11 06:55 UTC, Decodetalkers commented
> > 请问这个libdl.so来自哪个包呢
> 
> glibc

请问您能加一下commit的Log,然后按照CLA处理下吗

2022-08-12 00:38 UTC, kegechen approved these changes

2022-08-12 00:41 UTC, kegechen requested changes
https://github.com/linuxdeepin/developer-center/wiki/Commit-%E6%8F%90%E4%BA%A4%E4%BF%A1%E6%81%AF%E8%A7%84%E8%8C%83
按照规范需要将 `log:` 改成 `Log:`

2022-08-13 07:59 UTC, hillwoodroc commented
I have read the CLA Document and I hereby sign the CLA.

2022-08-13 09:56 UTC, Decodetalkers commented
> I have read the CLA Document and I hereby sign the CLA.

commit里的Fix改成fix应该就没问题了

2022-08-15 02:47 UTC, kegechen approved these changes

2022-08-15 06:55 UTC, merged